package lb.rest.user.db.entity;

import fc.wpf.rest.utils.CustomDateSerializer;
import fc.wpf.rest.web.bean.Tab;
import java.util.Date;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="mlbuser_auth_record")
public class MlbuserAuthRecord extends MlbuserAuthRecordKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mlbuser_auth_record.user_id
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mlbuser_auth_record.user_name
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mlbuser_auth_record.trade_manager_id
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    private Integer tradeManagerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mlbuser_auth_record.trade_manager_name
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    private String tradeManagerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mlbuser_auth_record.trade_person_id
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    private Integer tradePersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mlbuser_auth_record.trade_person_name
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    private String tradePersonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mlbuser_auth_record.client_id
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    private Integer clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mlbuser_auth_record.client_name
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    private String clientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mlbuser_auth_record.remark
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mlbuser_auth_record.create_time
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mlbuser_auth_record.modify_time
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mlbuser_auth_record.user_id
     *
     * @return the value of mlbuser_auth_record.user_id
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mlbuser_auth_record.user_id
     *
     * @param userId the value for mlbuser_auth_record.user_id
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mlbuser_auth_record.user_name
     *
     * @return the value of mlbuser_auth_record.user_name
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mlbuser_auth_record.user_name
     *
     * @param userName the value for mlbuser_auth_record.user_name
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mlbuser_auth_record.trade_manager_id
     *
     * @return the value of mlbuser_auth_record.trade_manager_id
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public Integer getTradeManagerId() {
        return tradeManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mlbuser_auth_record.trade_manager_id
     *
     * @param tradeManagerId the value for mlbuser_auth_record.trade_manager_id
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public void setTradeManagerId(Integer tradeManagerId) {
        this.tradeManagerId = tradeManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mlbuser_auth_record.trade_manager_name
     *
     * @return the value of mlbuser_auth_record.trade_manager_name
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public String getTradeManagerName() {
        return tradeManagerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mlbuser_auth_record.trade_manager_name
     *
     * @param tradeManagerName the value for mlbuser_auth_record.trade_manager_name
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public void setTradeManagerName(String tradeManagerName) {
        this.tradeManagerName = tradeManagerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mlbuser_auth_record.trade_person_id
     *
     * @return the value of mlbuser_auth_record.trade_person_id
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public Integer getTradePersonId() {
        return tradePersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mlbuser_auth_record.trade_person_id
     *
     * @param tradePersonId the value for mlbuser_auth_record.trade_person_id
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public void setTradePersonId(Integer tradePersonId) {
        this.tradePersonId = tradePersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mlbuser_auth_record.trade_person_name
     *
     * @return the value of mlbuser_auth_record.trade_person_name
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public String getTradePersonName() {
        return tradePersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mlbuser_auth_record.trade_person_name
     *
     * @param tradePersonName the value for mlbuser_auth_record.trade_person_name
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public void setTradePersonName(String tradePersonName) {
        this.tradePersonName = tradePersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mlbuser_auth_record.client_id
     *
     * @return the value of mlbuser_auth_record.client_id
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mlbuser_auth_record.client_id
     *
     * @param clientId the value for mlbuser_auth_record.client_id
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mlbuser_auth_record.client_name
     *
     * @return the value of mlbuser_auth_record.client_name
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mlbuser_auth_record.client_name
     *
     * @param clientName the value for mlbuser_auth_record.client_name
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mlbuser_auth_record.remark
     *
     * @return the value of mlbuser_auth_record.remark
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mlbuser_auth_record.remark
     *
     * @param remark the value for mlbuser_auth_record.remark
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mlbuser_auth_record.create_time
     *
     * @return the value of mlbuser_auth_record.create_time
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mlbuser_auth_record.create_time
     *
     * @param createTime the value for mlbuser_auth_record.create_time
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mlbuser_auth_record.modify_time
     *
     * @return the value of mlbuser_auth_record.modify_time
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mlbuser_auth_record.modify_time
     *
     * @param modifyTime the value for mlbuser_auth_record.modify_time
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_auth_record
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MlbuserAuthRecord other = (MlbuserAuthRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getTradeManagerId() == null ? other.getTradeManagerId() == null : this.getTradeManagerId().equals(other.getTradeManagerId()))
            && (this.getTradeManagerName() == null ? other.getTradeManagerName() == null : this.getTradeManagerName().equals(other.getTradeManagerName()))
            && (this.getTradePersonId() == null ? other.getTradePersonId() == null : this.getTradePersonId().equals(other.getTradePersonId()))
            && (this.getTradePersonName() == null ? other.getTradePersonName() == null : this.getTradePersonName().equals(other.getTradePersonName()))
            && (this.getClientId() == null ? other.getClientId() == null : this.getClientId().equals(other.getClientId()))
            && (this.getClientName() == null ? other.getClientName() == null : this.getClientName().equals(other.getClientName()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_auth_record
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getTradeManagerId() == null) ? 0 : getTradeManagerId().hashCode());
        result = prime * result + ((getTradeManagerName() == null) ? 0 : getTradeManagerName().hashCode());
        result = prime * result + ((getTradePersonId() == null) ? 0 : getTradePersonId().hashCode());
        result = prime * result + ((getTradePersonName() == null) ? 0 : getTradePersonName().hashCode());
        result = prime * result + ((getClientId() == null) ? 0 : getClientId().hashCode());
        result = prime * result + ((getClientName() == null) ? 0 : getClientName().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_auth_record
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", tradeManagerId=").append(tradeManagerId);
        sb.append(", tradeManagerName=").append(tradeManagerName);
        sb.append(", tradePersonId=").append(tradePersonId);
        sb.append(", tradePersonName=").append(tradePersonName);
        sb.append(", clientId=").append(clientId);
        sb.append(", clientName=").append(clientName);
        sb.append(", remark=").append(remark);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append("]");
        return sb.toString();
    }
}