package lb.rest.user.db.entity;

import java.util.Date;

public class BsUserComment extends BsUserCommentKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_comment.user_id
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_comment.comment_time
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    private Date commentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_comment.commentator_id
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    private Integer commentatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_comment.commentator_name
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    private String commentatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_comment.comment_level
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    private Integer commentLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_comment.content
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_comment.remark
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_comment.from_type
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    private Integer fromType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_comment.has_read
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    private Integer hasRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_comment.int_column1
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    private Integer intColumn1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_comment.int_column2
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    private Integer intColumn2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_comment.str_column1
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    private String strColumn1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_comment.str_column2
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    private String strColumn2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_comment.user_id
     *
     * @return the value of bs_user_comment.user_id
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_comment.user_id
     *
     * @param userId the value for bs_user_comment.user_id
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_comment.comment_time
     *
     * @return the value of bs_user_comment.comment_time
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public Date getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_comment.comment_time
     *
     * @param commentTime the value for bs_user_comment.comment_time
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_comment.commentator_id
     *
     * @return the value of bs_user_comment.commentator_id
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public Integer getCommentatorId() {
        return commentatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_comment.commentator_id
     *
     * @param commentatorId the value for bs_user_comment.commentator_id
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public void setCommentatorId(Integer commentatorId) {
        this.commentatorId = commentatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_comment.commentator_name
     *
     * @return the value of bs_user_comment.commentator_name
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public String getCommentatorName() {
        return commentatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_comment.commentator_name
     *
     * @param commentatorName the value for bs_user_comment.commentator_name
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public void setCommentatorName(String commentatorName) {
        this.commentatorName = commentatorName == null ? null : commentatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_comment.comment_level
     *
     * @return the value of bs_user_comment.comment_level
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public Integer getCommentLevel() {
        return commentLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_comment.comment_level
     *
     * @param commentLevel the value for bs_user_comment.comment_level
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public void setCommentLevel(Integer commentLevel) {
        this.commentLevel = commentLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_comment.content
     *
     * @return the value of bs_user_comment.content
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_comment.content
     *
     * @param content the value for bs_user_comment.content
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_comment.remark
     *
     * @return the value of bs_user_comment.remark
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_comment.remark
     *
     * @param remark the value for bs_user_comment.remark
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_comment.from_type
     *
     * @return the value of bs_user_comment.from_type
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public Integer getFromType() {
        return fromType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_comment.from_type
     *
     * @param fromType the value for bs_user_comment.from_type
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public void setFromType(Integer fromType) {
        this.fromType = fromType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_comment.has_read
     *
     * @return the value of bs_user_comment.has_read
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public Integer getHasRead() {
        return hasRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_comment.has_read
     *
     * @param hasRead the value for bs_user_comment.has_read
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public void setHasRead(Integer hasRead) {
        this.hasRead = hasRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_comment.int_column1
     *
     * @return the value of bs_user_comment.int_column1
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public Integer getIntColumn1() {
        return intColumn1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_comment.int_column1
     *
     * @param intColumn1 the value for bs_user_comment.int_column1
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public void setIntColumn1(Integer intColumn1) {
        this.intColumn1 = intColumn1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_comment.int_column2
     *
     * @return the value of bs_user_comment.int_column2
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public Integer getIntColumn2() {
        return intColumn2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_comment.int_column2
     *
     * @param intColumn2 the value for bs_user_comment.int_column2
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public void setIntColumn2(Integer intColumn2) {
        this.intColumn2 = intColumn2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_comment.str_column1
     *
     * @return the value of bs_user_comment.str_column1
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public String getStrColumn1() {
        return strColumn1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_comment.str_column1
     *
     * @param strColumn1 the value for bs_user_comment.str_column1
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public void setStrColumn1(String strColumn1) {
        this.strColumn1 = strColumn1 == null ? null : strColumn1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_comment.str_column2
     *
     * @return the value of bs_user_comment.str_column2
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public String getStrColumn2() {
        return strColumn2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_comment.str_column2
     *
     * @param strColumn2 the value for bs_user_comment.str_column2
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    public void setStrColumn2(String strColumn2) {
        this.strColumn2 = strColumn2 == null ? null : strColumn2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user_comment
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", commentTime=").append(commentTime);
        sb.append(", commentatorId=").append(commentatorId);
        sb.append(", commentatorName=").append(commentatorName);
        sb.append(", commentLevel=").append(commentLevel);
        sb.append(", content=").append(content);
        sb.append(", remark=").append(remark);
        sb.append(", fromType=").append(fromType);
        sb.append(", hasRead=").append(hasRead);
        sb.append(", intColumn1=").append(intColumn1);
        sb.append(", intColumn2=").append(intColumn2);
        sb.append(", strColumn1=").append(strColumn1);
        sb.append(", strColumn2=").append(strColumn2);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user_comment
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BsUserComment other = (BsUserComment) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getCommentTime() == null ? other.getCommentTime() == null : this.getCommentTime().equals(other.getCommentTime()))
            && (this.getCommentatorId() == null ? other.getCommentatorId() == null : this.getCommentatorId().equals(other.getCommentatorId()))
            && (this.getCommentatorName() == null ? other.getCommentatorName() == null : this.getCommentatorName().equals(other.getCommentatorName()))
            && (this.getCommentLevel() == null ? other.getCommentLevel() == null : this.getCommentLevel().equals(other.getCommentLevel()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getFromType() == null ? other.getFromType() == null : this.getFromType().equals(other.getFromType()))
            && (this.getHasRead() == null ? other.getHasRead() == null : this.getHasRead().equals(other.getHasRead()))
            && (this.getIntColumn1() == null ? other.getIntColumn1() == null : this.getIntColumn1().equals(other.getIntColumn1()))
            && (this.getIntColumn2() == null ? other.getIntColumn2() == null : this.getIntColumn2().equals(other.getIntColumn2()))
            && (this.getStrColumn1() == null ? other.getStrColumn1() == null : this.getStrColumn1().equals(other.getStrColumn1()))
            && (this.getStrColumn2() == null ? other.getStrColumn2() == null : this.getStrColumn2().equals(other.getStrColumn2()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user_comment
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getCommentTime() == null) ? 0 : getCommentTime().hashCode());
        result = prime * result + ((getCommentatorId() == null) ? 0 : getCommentatorId().hashCode());
        result = prime * result + ((getCommentatorName() == null) ? 0 : getCommentatorName().hashCode());
        result = prime * result + ((getCommentLevel() == null) ? 0 : getCommentLevel().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getFromType() == null) ? 0 : getFromType().hashCode());
        result = prime * result + ((getHasRead() == null) ? 0 : getHasRead().hashCode());
        result = prime * result + ((getIntColumn1() == null) ? 0 : getIntColumn1().hashCode());
        result = prime * result + ((getIntColumn2() == null) ? 0 : getIntColumn2().hashCode());
        result = prime * result + ((getStrColumn1() == null) ? 0 : getStrColumn1().hashCode());
        result = prime * result + ((getStrColumn2() == null) ? 0 : getStrColumn2().hashCode());
        return result;
    }
}