package lb.rest.user.db.entity;

import fc.wpf.rest.web.bean.Tab;

@Tab(name = "common_attr_type")
public class CommonAttrType extends CommonAttrTypeKey {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column common_attr_type.typeName
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	private String typename;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column common_attr_type.isAvailable
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	private Integer isavailable;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column common_attr_type.createTime
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	private String createtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column common_attr_type.isTag
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	private Integer istag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column common_attr_type.tagCategory
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	private Integer tagcategory;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column common_attr_type.typeName
	 *
	 * @return the value of common_attr_type.typeName
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	public String getTypename() {
		return typename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column common_attr_type.typeName
	 *
	 * @param typename
	 *            the value for common_attr_type.typeName
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	public void setTypename(String typename) {
		this.typename = typename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column common_attr_type.isAvailable
	 *
	 * @return the value of common_attr_type.isAvailable
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	public Integer getIsavailable() {
		return isavailable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column common_attr_type.isAvailable
	 *
	 * @param isavailable
	 *            the value for common_attr_type.isAvailable
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	public void setIsavailable(Integer isavailable) {
		this.isavailable = isavailable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column common_attr_type.createTime
	 *
	 * @return the value of common_attr_type.createTime
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	public String getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column common_attr_type.createTime
	 *
	 * @param createtime
	 *            the value for common_attr_type.createTime
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column common_attr_type.isTag
	 *
	 * @return the value of common_attr_type.isTag
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	public Integer getIstag() {
		return istag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column common_attr_type.isTag
	 *
	 * @param istag
	 *            the value for common_attr_type.isTag
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	public void setIstag(Integer istag) {
		this.istag = istag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column common_attr_type.tagCategory
	 *
	 * @return the value of common_attr_type.tagCategory
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	public Integer getTagcategory() {
		return tagcategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column common_attr_type.tagCategory
	 *
	 * @param tagcategory
	 *            the value for common_attr_type.tagCategory
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	public void setTagcategory(Integer tagcategory) {
		this.tagcategory = tagcategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table common_attr_type
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		CommonAttrType other = (CommonAttrType) that;
		return (this.getTypeid() == null ? other.getTypeid() == null : this.getTypeid().equals(other.getTypeid()))
				&& (this.getTypename() == null ? other.getTypename() == null : this.getTypename().equals(
						other.getTypename()))
				&& (this.getIsavailable() == null ? other.getIsavailable() == null : this.getIsavailable().equals(
						other.getIsavailable()))
				&& (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(
						other.getCreatetime()))
				&& (this.getIstag() == null ? other.getIstag() == null : this.getIstag().equals(other.getIstag()))
				&& (this.getTagcategory() == null ? other.getTagcategory() == null : this.getTagcategory().equals(
						other.getTagcategory()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table common_attr_type
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getTypeid() == null) ? 0 : getTypeid().hashCode());
		result = prime * result + ((getTypename() == null) ? 0 : getTypename().hashCode());
		result = prime * result + ((getIsavailable() == null) ? 0 : getIsavailable().hashCode());
		result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
		result = prime * result + ((getIstag() == null) ? 0 : getIstag().hashCode());
		result = prime * result + ((getTagcategory() == null) ? 0 : getTagcategory().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table common_attr_type
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", typename=").append(typename);
		sb.append(", isavailable=").append(isavailable);
		sb.append(", createtime=").append(createtime);
		sb.append(", istag=").append(istag);
		sb.append(", tagcategory=").append(tagcategory);
		sb.append("]");
		return sb.toString();
	}
}