package lb.rest.user.db.entity;

import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import fc.wpf.rest.utils.CustomDateSerializer;
import fc.wpf.rest.web.bean.Tab;

@Tab(name = "mlb_rejection_dispose")
public class MlbRejectionDispose extends MlbRejectionDisposeKey {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mlb_rejection_dispose.user_id
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mlb_rejection_dispose.user_name
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	private String userName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mlb_rejection_dispose.user_phone
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	private String userPhone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mlb_rejection_dispose.apply_time
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	private Date applyTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mlb_rejection_dispose.operation_time
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	private Date operationTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mlb_rejection_dispose.operation_user_id
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	private Integer operationUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mlb_rejection_dispose.operation_user_name
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	private String operationUserName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mlb_rejection_dispose.location
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	private Integer location;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mlb_rejection_dispose.location_desc
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	private String locationDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mlb_rejection_dispose.address
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mlb_rejection_dispose.grain_type
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	private Integer grainType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mlb_rejection_dispose.grain_level
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	private Integer grainLevel;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mlb_rejection_dispose.quality_desc
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	private String qualityDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mlb_rejection_dispose.price
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	private Double price;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mlb_rejection_dispose.amount
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	private Double amount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mlb_rejection_dispose.has_invoice
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	private Integer hasInvoice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mlb_rejection_dispose.remark
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	private String remark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mlb_rejection_dispose.str_column_bak1
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	private String strColumnBak1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mlb_rejection_dispose.int_column_bak1
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	private Integer intColumnBak1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column mlb_rejection_dispose.status
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mlb_rejection_dispose.user_id
	 *
	 * @return the value of mlb_rejection_dispose.user_id
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mlb_rejection_dispose.user_id
	 *
	 * @param userId
	 *            the value for mlb_rejection_dispose.user_id
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mlb_rejection_dispose.user_name
	 *
	 * @return the value of mlb_rejection_dispose.user_name
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mlb_rejection_dispose.user_name
	 *
	 * @param userName
	 *            the value for mlb_rejection_dispose.user_name
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mlb_rejection_dispose.user_phone
	 *
	 * @return the value of mlb_rejection_dispose.user_phone
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public String getUserPhone() {
		return userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mlb_rejection_dispose.user_phone
	 *
	 * @param userPhone
	 *            the value for mlb_rejection_dispose.user_phone
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mlb_rejection_dispose.apply_time
	 *
	 * @return the value of mlb_rejection_dispose.apply_time
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	@JsonSerialize(using = CustomDateSerializer.class)
	public Date getApplyTime() {
		return applyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mlb_rejection_dispose.apply_time
	 *
	 * @param applyTime
	 *            the value for mlb_rejection_dispose.apply_time
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public void setApplyTime(Date applyTime) {
		this.applyTime = applyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mlb_rejection_dispose.operation_time
	 *
	 * @return the value of mlb_rejection_dispose.operation_time
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	@JsonSerialize(using = CustomDateSerializer.class)
	public Date getOperationTime() {
		return operationTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mlb_rejection_dispose.operation_time
	 *
	 * @param operationTime
	 *            the value for mlb_rejection_dispose.operation_time
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public void setOperationTime(Date operationTime) {
		this.operationTime = operationTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mlb_rejection_dispose.operation_user_id
	 *
	 * @return the value of mlb_rejection_dispose.operation_user_id
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public Integer getOperationUserId() {
		return operationUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mlb_rejection_dispose.operation_user_id
	 *
	 * @param operationUserId
	 *            the value for mlb_rejection_dispose.operation_user_id
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public void setOperationUserId(Integer operationUserId) {
		this.operationUserId = operationUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mlb_rejection_dispose.operation_user_name
	 *
	 * @return the value of mlb_rejection_dispose.operation_user_name
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public String getOperationUserName() {
		return operationUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mlb_rejection_dispose.operation_user_name
	 *
	 * @param operationUserName
	 *            the value for mlb_rejection_dispose.operation_user_name
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public void setOperationUserName(String operationUserName) {
		this.operationUserName = operationUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mlb_rejection_dispose.location
	 *
	 * @return the value of mlb_rejection_dispose.location
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public Integer getLocation() {
		return location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mlb_rejection_dispose.location
	 *
	 * @param location
	 *            the value for mlb_rejection_dispose.location
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public void setLocation(Integer location) {
		this.location = location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mlb_rejection_dispose.location_desc
	 *
	 * @return the value of mlb_rejection_dispose.location_desc
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public String getLocationDesc() {
		return locationDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mlb_rejection_dispose.location_desc
	 *
	 * @param locationDesc
	 *            the value for mlb_rejection_dispose.location_desc
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public void setLocationDesc(String locationDesc) {
		this.locationDesc = locationDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mlb_rejection_dispose.address
	 *
	 * @return the value of mlb_rejection_dispose.address
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mlb_rejection_dispose.address
	 *
	 * @param address
	 *            the value for mlb_rejection_dispose.address
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mlb_rejection_dispose.grain_type
	 *
	 * @return the value of mlb_rejection_dispose.grain_type
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public Integer getGrainType() {
		return grainType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mlb_rejection_dispose.grain_type
	 *
	 * @param grainType
	 *            the value for mlb_rejection_dispose.grain_type
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public void setGrainType(Integer grainType) {
		this.grainType = grainType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mlb_rejection_dispose.grain_level
	 *
	 * @return the value of mlb_rejection_dispose.grain_level
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public Integer getGrainLevel() {
		return grainLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mlb_rejection_dispose.grain_level
	 *
	 * @param grainLevel
	 *            the value for mlb_rejection_dispose.grain_level
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public void setGrainLevel(Integer grainLevel) {
		this.grainLevel = grainLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mlb_rejection_dispose.quality_desc
	 *
	 * @return the value of mlb_rejection_dispose.quality_desc
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public String getQualityDesc() {
		return qualityDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mlb_rejection_dispose.quality_desc
	 *
	 * @param qualityDesc
	 *            the value for mlb_rejection_dispose.quality_desc
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public void setQualityDesc(String qualityDesc) {
		this.qualityDesc = qualityDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mlb_rejection_dispose.price
	 *
	 * @return the value of mlb_rejection_dispose.price
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mlb_rejection_dispose.price
	 *
	 * @param price
	 *            the value for mlb_rejection_dispose.price
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mlb_rejection_dispose.amount
	 *
	 * @return the value of mlb_rejection_dispose.amount
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public Double getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mlb_rejection_dispose.amount
	 *
	 * @param amount
	 *            the value for mlb_rejection_dispose.amount
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mlb_rejection_dispose.has_invoice
	 *
	 * @return the value of mlb_rejection_dispose.has_invoice
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public Integer getHasInvoice() {
		return hasInvoice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mlb_rejection_dispose.has_invoice
	 *
	 * @param hasInvoice
	 *            the value for mlb_rejection_dispose.has_invoice
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public void setHasInvoice(Integer hasInvoice) {
		this.hasInvoice = hasInvoice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mlb_rejection_dispose.remark
	 *
	 * @return the value of mlb_rejection_dispose.remark
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mlb_rejection_dispose.remark
	 *
	 * @param remark
	 *            the value for mlb_rejection_dispose.remark
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mlb_rejection_dispose.str_column_bak1
	 *
	 * @return the value of mlb_rejection_dispose.str_column_bak1
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public String getStrColumnBak1() {
		return strColumnBak1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mlb_rejection_dispose.str_column_bak1
	 *
	 * @param strColumnBak1
	 *            the value for mlb_rejection_dispose.str_column_bak1
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public void setStrColumnBak1(String strColumnBak1) {
		this.strColumnBak1 = strColumnBak1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mlb_rejection_dispose.int_column_bak1
	 *
	 * @return the value of mlb_rejection_dispose.int_column_bak1
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public Integer getIntColumnBak1() {
		return intColumnBak1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mlb_rejection_dispose.int_column_bak1
	 *
	 * @param intColumnBak1
	 *            the value for mlb_rejection_dispose.int_column_bak1
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public void setIntColumnBak1(Integer intColumnBak1) {
		this.intColumnBak1 = intColumnBak1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column mlb_rejection_dispose.status
	 *
	 * @return the value of mlb_rejection_dispose.status
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column mlb_rejection_dispose.status
	 *
	 * @param status
	 *            the value for mlb_rejection_dispose.status
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table mlb_rejection_dispose
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		MlbRejectionDispose other = (MlbRejectionDispose) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
				&& (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(
						other.getUserName()))
				&& (this.getUserPhone() == null ? other.getUserPhone() == null : this.getUserPhone().equals(
						other.getUserPhone()))
				&& (this.getApplyTime() == null ? other.getApplyTime() == null : this.getApplyTime().equals(
						other.getApplyTime()))
				&& (this.getOperationTime() == null ? other.getOperationTime() == null : this.getOperationTime()
						.equals(other.getOperationTime()))
				&& (this.getOperationUserId() == null ? other.getOperationUserId() == null : this.getOperationUserId()
						.equals(other.getOperationUserId()))
				&& (this.getOperationUserName() == null ? other.getOperationUserName() == null : this
						.getOperationUserName().equals(other.getOperationUserName()))
				&& (this.getLocation() == null ? other.getLocation() == null : this.getLocation().equals(
						other.getLocation()))
				&& (this.getLocationDesc() == null ? other.getLocationDesc() == null : this.getLocationDesc().equals(
						other.getLocationDesc()))
				&& (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(
						other.getAddress()))
				&& (this.getGrainType() == null ? other.getGrainType() == null : this.getGrainType().equals(
						other.getGrainType()))
				&& (this.getGrainLevel() == null ? other.getGrainLevel() == null : this.getGrainLevel().equals(
						other.getGrainLevel()))
				&& (this.getQualityDesc() == null ? other.getQualityDesc() == null : this.getQualityDesc().equals(
						other.getQualityDesc()))
				&& (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
				&& (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
				&& (this.getHasInvoice() == null ? other.getHasInvoice() == null : this.getHasInvoice().equals(
						other.getHasInvoice()))
				&& (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
				&& (this.getStrColumnBak1() == null ? other.getStrColumnBak1() == null : this.getStrColumnBak1()
						.equals(other.getStrColumnBak1()))
				&& (this.getIntColumnBak1() == null ? other.getIntColumnBak1() == null : this.getIntColumnBak1()
						.equals(other.getIntColumnBak1()))
				&& (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table mlb_rejection_dispose
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
		result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
		result = prime * result + ((getUserPhone() == null) ? 0 : getUserPhone().hashCode());
		result = prime * result + ((getApplyTime() == null) ? 0 : getApplyTime().hashCode());
		result = prime * result + ((getOperationTime() == null) ? 0 : getOperationTime().hashCode());
		result = prime * result + ((getOperationUserId() == null) ? 0 : getOperationUserId().hashCode());
		result = prime * result + ((getOperationUserName() == null) ? 0 : getOperationUserName().hashCode());
		result = prime * result + ((getLocation() == null) ? 0 : getLocation().hashCode());
		result = prime * result + ((getLocationDesc() == null) ? 0 : getLocationDesc().hashCode());
		result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
		result = prime * result + ((getGrainType() == null) ? 0 : getGrainType().hashCode());
		result = prime * result + ((getGrainLevel() == null) ? 0 : getGrainLevel().hashCode());
		result = prime * result + ((getQualityDesc() == null) ? 0 : getQualityDesc().hashCode());
		result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
		result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
		result = prime * result + ((getHasInvoice() == null) ? 0 : getHasInvoice().hashCode());
		result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
		result = prime * result + ((getStrColumnBak1() == null) ? 0 : getStrColumnBak1().hashCode());
		result = prime * result + ((getIntColumnBak1() == null) ? 0 : getIntColumnBak1().hashCode());
		result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table mlb_rejection_dispose
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", userId=").append(userId);
		sb.append(", userName=").append(userName);
		sb.append(", userPhone=").append(userPhone);
		sb.append(", applyTime=").append(applyTime);
		sb.append(", operationTime=").append(operationTime);
		sb.append(", operationUserId=").append(operationUserId);
		sb.append(", operationUserName=").append(operationUserName);
		sb.append(", location=").append(location);
		sb.append(", locationDesc=").append(locationDesc);
		sb.append(", address=").append(address);
		sb.append(", grainType=").append(grainType);
		sb.append(", grainLevel=").append(grainLevel);
		sb.append(", qualityDesc=").append(qualityDesc);
		sb.append(", price=").append(price);
		sb.append(", amount=").append(amount);
		sb.append(", hasInvoice=").append(hasInvoice);
		sb.append(", remark=").append(remark);
		sb.append(", strColumnBak1=").append(strColumnBak1);
		sb.append(", intColumnBak1=").append(intColumnBak1);
		sb.append(", status=").append(status);
		sb.append("]");
		return sb.toString();
	}
}