package lb.rest.user.db.mapper;

import java.util.List;
import lb.rest.user.db.entity.BsAttention;
import lb.rest.user.db.entity.BsAttentionExample;
import lb.rest.user.db.entity.BsAttentionKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface BsAttentionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_attention
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @SelectProvider(type=BsAttentionSqlProvider.class, method="countByExample")
    int countByExample(BsAttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_attention
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @DeleteProvider(type=BsAttentionSqlProvider.class, method="deleteByExample")
    int deleteByExample(BsAttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_attention
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @Delete({
        "delete from bs_attention",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(BsAttentionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_attention
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @Insert({
        "insert into bs_attention (id, subject_user_id, ",
        "subject_user_name, object_user_id, ",
        "object_user_name, object_user_phone, ",
        "status, attention_time, ",
        "remark)",
        "values (#{id,jdbcType=INTEGER}, #{subjectUserId,jdbcType=INTEGER}, ",
        "#{subjectUserName,jdbcType=VARCHAR}, #{objectUserId,jdbcType=INTEGER}, ",
        "#{objectUserName,jdbcType=VARCHAR}, #{objectUserPhone,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=INTEGER}, #{attentionTime,jdbcType=TIMESTAMP}, ",
        "#{remark,jdbcType=VARCHAR})"
    })
    int insert(BsAttention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_attention
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @InsertProvider(type=BsAttentionSqlProvider.class, method="insertSelective")
    int insertSelective(BsAttention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_attention
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @SelectProvider(type=BsAttentionSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="subject_user_id", property="subjectUserId", jdbcType=JdbcType.INTEGER),
        @Result(column="subject_user_name", property="subjectUserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="object_user_id", property="objectUserId", jdbcType=JdbcType.INTEGER),
        @Result(column="object_user_name", property="objectUserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="object_user_phone", property="objectUserPhone", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="attention_time", property="attentionTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<BsAttention> selectByExample(BsAttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_attention
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @Select({
        "select",
        "id, subject_user_id, subject_user_name, object_user_id, object_user_name, object_user_phone, ",
        "status, attention_time, remark",
        "from bs_attention",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="subject_user_id", property="subjectUserId", jdbcType=JdbcType.INTEGER),
        @Result(column="subject_user_name", property="subjectUserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="object_user_id", property="objectUserId", jdbcType=JdbcType.INTEGER),
        @Result(column="object_user_name", property="objectUserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="object_user_phone", property="objectUserPhone", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="attention_time", property="attentionTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    BsAttention selectByPrimaryKey(BsAttentionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_attention
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @UpdateProvider(type=BsAttentionSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BsAttention record, @Param("example") BsAttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_attention
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @UpdateProvider(type=BsAttentionSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BsAttention record, @Param("example") BsAttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_attention
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @UpdateProvider(type=BsAttentionSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BsAttention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_attention
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @Update({
        "update bs_attention",
        "set subject_user_id = #{subjectUserId,jdbcType=INTEGER},",
          "subject_user_name = #{subjectUserName,jdbcType=VARCHAR},",
          "object_user_id = #{objectUserId,jdbcType=INTEGER},",
          "object_user_name = #{objectUserName,jdbcType=VARCHAR},",
          "object_user_phone = #{objectUserPhone,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "attention_time = #{attentionTime,jdbcType=TIMESTAMP},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BsAttention record);
}