package lb.rest.user.db.mapper;

import java.util.List;
import lb.rest.user.db.entity.BsUserAbstract;
import lb.rest.user.db.entity.BsUserAbstractExample;
import lb.rest.user.db.entity.BsUserAbstractKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface BsUserAbstractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user_abstract
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @SelectProvider(type=BsUserAbstractSqlProvider.class, method="countByExample")
    int countByExample(BsUserAbstractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user_abstract
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @DeleteProvider(type=BsUserAbstractSqlProvider.class, method="deleteByExample")
    int deleteByExample(BsUserAbstractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user_abstract
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @Delete({
        "delete from bs_user_abstract",
        "where user_id = #{userId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(BsUserAbstractKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user_abstract
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @Insert({
        "insert into bs_user_abstract (user_id, company_abstract)",
        "values (#{userId,jdbcType=INTEGER}, #{companyAbstract,jdbcType=VARCHAR})"
    })
    int insert(BsUserAbstract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user_abstract
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @InsertProvider(type=BsUserAbstractSqlProvider.class, method="insertSelective")
    int insertSelective(BsUserAbstract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user_abstract
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @SelectProvider(type=BsUserAbstractSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="company_abstract", property="companyAbstract", jdbcType=JdbcType.VARCHAR)
    })
    List<BsUserAbstract> selectByExample(BsUserAbstractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user_abstract
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @Select({
        "select",
        "user_id, company_abstract",
        "from bs_user_abstract",
        "where user_id = #{userId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="company_abstract", property="companyAbstract", jdbcType=JdbcType.VARCHAR)
    })
    BsUserAbstract selectByPrimaryKey(BsUserAbstractKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user_abstract
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @UpdateProvider(type=BsUserAbstractSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BsUserAbstract record, @Param("example") BsUserAbstractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user_abstract
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @UpdateProvider(type=BsUserAbstractSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BsUserAbstract record, @Param("example") BsUserAbstractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user_abstract
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @UpdateProvider(type=BsUserAbstractSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BsUserAbstract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user_abstract
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @Update({
        "update bs_user_abstract",
        "set company_abstract = #{companyAbstract,jdbcType=VARCHAR}",
        "where user_id = #{userId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BsUserAbstract record);
}