package lb.rest.user.db.mapper;

import java.util.List;
import lb.rest.user.db.entity.BsAdvertPosition;
import lb.rest.user.db.entity.BsAdvertPositionExample;
import lb.rest.user.db.entity.BsAdvertPositionKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface BsAdvertPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_advert_position
     *
     * @mbggenerated Thu Jul 06 14:40:44 CST 2017
     */
    @SelectProvider(type=BsAdvertPositionSqlProvider.class, method="countByExample")
    int countByExample(BsAdvertPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_advert_position
     *
     * @mbggenerated Thu Jul 06 14:40:44 CST 2017
     */
    @DeleteProvider(type=BsAdvertPositionSqlProvider.class, method="deleteByExample")
    int deleteByExample(BsAdvertPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_advert_position
     *
     * @mbggenerated Thu Jul 06 14:40:44 CST 2017
     */
    @Delete({
        "delete from bs_advert_position",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(BsAdvertPositionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_advert_position
     *
     * @mbggenerated Thu Jul 06 14:40:44 CST 2017
     */
    @Insert({
        "insert into bs_advert_position (id, advert_type, ",
        "title, content, ",
        "user_id, user_name, ",
        "user_phone, rank, ",
        "status, operate_user_id, ",
        "operate_user_name, create_time, ",
        "update_time, int_column1, ",
        "int_column2, str_column1, ",
        "str_column2)",
        "values (#{id,jdbcType=INTEGER}, #{advertType,jdbcType=INTEGER}, ",
        "#{title,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR}, ",
        "#{userId,jdbcType=INTEGER}, #{userName,jdbcType=VARCHAR}, ",
        "#{userPhone,jdbcType=VARCHAR}, #{rank,jdbcType=INTEGER}, ",
        "#{status,jdbcType=INTEGER}, #{operateUserId,jdbcType=INTEGER}, ",
        "#{operateUserName,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{intColumn1,jdbcType=INTEGER}, ",
        "#{intColumn2,jdbcType=INTEGER}, #{strColumn1,jdbcType=VARCHAR}, ",
        "#{strColumn2,jdbcType=VARCHAR})"
    })
    int insert(BsAdvertPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_advert_position
     *
     * @mbggenerated Thu Jul 06 14:40:44 CST 2017
     */
    @InsertProvider(type=BsAdvertPositionSqlProvider.class, method="insertSelective")
    int insertSelective(BsAdvertPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_advert_position
     *
     * @mbggenerated Thu Jul 06 14:40:44 CST 2017
     */
    @SelectProvider(type=BsAdvertPositionSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="advert_type", property="advertType", jdbcType=JdbcType.INTEGER),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_phone", property="userPhone", jdbcType=JdbcType.VARCHAR),
        @Result(column="rank", property="rank", jdbcType=JdbcType.INTEGER),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="operate_user_id", property="operateUserId", jdbcType=JdbcType.INTEGER),
        @Result(column="operate_user_name", property="operateUserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="int_column1", property="intColumn1", jdbcType=JdbcType.INTEGER),
        @Result(column="int_column2", property="intColumn2", jdbcType=JdbcType.INTEGER),
        @Result(column="str_column1", property="strColumn1", jdbcType=JdbcType.VARCHAR),
        @Result(column="str_column2", property="strColumn2", jdbcType=JdbcType.VARCHAR)
    })
    List<BsAdvertPosition> selectByExample(BsAdvertPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_advert_position
     *
     * @mbggenerated Thu Jul 06 14:40:44 CST 2017
     */
    @Select({
        "select",
        "id, advert_type, title, content, user_id, user_name, user_phone, rank, status, ",
        "operate_user_id, operate_user_name, create_time, update_time, int_column1, int_column2, ",
        "str_column1, str_column2",
        "from bs_advert_position",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="advert_type", property="advertType", jdbcType=JdbcType.INTEGER),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_phone", property="userPhone", jdbcType=JdbcType.VARCHAR),
        @Result(column="rank", property="rank", jdbcType=JdbcType.INTEGER),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="operate_user_id", property="operateUserId", jdbcType=JdbcType.INTEGER),
        @Result(column="operate_user_name", property="operateUserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="int_column1", property="intColumn1", jdbcType=JdbcType.INTEGER),
        @Result(column="int_column2", property="intColumn2", jdbcType=JdbcType.INTEGER),
        @Result(column="str_column1", property="strColumn1", jdbcType=JdbcType.VARCHAR),
        @Result(column="str_column2", property="strColumn2", jdbcType=JdbcType.VARCHAR)
    })
    BsAdvertPosition selectByPrimaryKey(BsAdvertPositionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_advert_position
     *
     * @mbggenerated Thu Jul 06 14:40:44 CST 2017
     */
    @UpdateProvider(type=BsAdvertPositionSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BsAdvertPosition record, @Param("example") BsAdvertPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_advert_position
     *
     * @mbggenerated Thu Jul 06 14:40:44 CST 2017
     */
    @UpdateProvider(type=BsAdvertPositionSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BsAdvertPosition record, @Param("example") BsAdvertPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_advert_position
     *
     * @mbggenerated Thu Jul 06 14:40:44 CST 2017
     */
    @UpdateProvider(type=BsAdvertPositionSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BsAdvertPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_advert_position
     *
     * @mbggenerated Thu Jul 06 14:40:44 CST 2017
     */
    @Update({
        "update bs_advert_position",
        "set advert_type = #{advertType,jdbcType=INTEGER},",
          "title = #{title,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "user_name = #{userName,jdbcType=VARCHAR},",
          "user_phone = #{userPhone,jdbcType=VARCHAR},",
          "rank = #{rank,jdbcType=INTEGER},",
          "status = #{status,jdbcType=INTEGER},",
          "operate_user_id = #{operateUserId,jdbcType=INTEGER},",
          "operate_user_name = #{operateUserName,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "int_column1 = #{intColumn1,jdbcType=INTEGER},",
          "int_column2 = #{intColumn2,jdbcType=INTEGER},",
          "str_column1 = #{strColumn1,jdbcType=VARCHAR},",
          "str_column2 = #{strColumn2,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BsAdvertPosition record);
}