package lb.rest.user.db.mapper;

import java.util.List;
import lb.rest.user.db.entity.BsInventoryUserDepot;
import lb.rest.user.db.entity.BsInventoryUserDepotExample;
import lb.rest.user.db.entity.BsInventoryUserDepotKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface BsInventoryUserDepotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_user_depot
     *
     * @mbggenerated Mon May 15 11:54:35 CST 2017
     */
    @SelectProvider(type=BsInventoryUserDepotSqlProvider.class, method="countByExample")
    int countByExample(BsInventoryUserDepotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_user_depot
     *
     * @mbggenerated Mon May 15 11:54:35 CST 2017
     */
    @DeleteProvider(type=BsInventoryUserDepotSqlProvider.class, method="deleteByExample")
    int deleteByExample(BsInventoryUserDepotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_user_depot
     *
     * @mbggenerated Mon May 15 11:54:35 CST 2017
     */
    @Delete({
        "delete from bs_inventory_user_depot",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(BsInventoryUserDepotKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_user_depot
     *
     * @mbggenerated Mon May 15 11:54:35 CST 2017
     */
    @Insert({
        "insert into bs_inventory_user_depot (user_id, depot_id)",
        "values (#{userId,jdbcType=INTEGER}, #{depotId,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(BsInventoryUserDepot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_user_depot
     *
     * @mbggenerated Mon May 15 11:54:35 CST 2017
     */
    @InsertProvider(type=BsInventoryUserDepotSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(BsInventoryUserDepot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_user_depot
     *
     * @mbggenerated Mon May 15 11:54:35 CST 2017
     */
    @SelectProvider(type=BsInventoryUserDepotSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="depot_id", property="depotId", jdbcType=JdbcType.INTEGER)
    })
    List<BsInventoryUserDepot> selectByExample(BsInventoryUserDepotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_user_depot
     *
     * @mbggenerated Mon May 15 11:54:35 CST 2017
     */
    @Select({
        "select",
        "id, user_id, depot_id",
        "from bs_inventory_user_depot",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="depot_id", property="depotId", jdbcType=JdbcType.INTEGER)
    })
    BsInventoryUserDepot selectByPrimaryKey(BsInventoryUserDepotKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_user_depot
     *
     * @mbggenerated Mon May 15 11:54:35 CST 2017
     */
    @UpdateProvider(type=BsInventoryUserDepotSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BsInventoryUserDepot record, @Param("example") BsInventoryUserDepotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_user_depot
     *
     * @mbggenerated Mon May 15 11:54:35 CST 2017
     */
    @UpdateProvider(type=BsInventoryUserDepotSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BsInventoryUserDepot record, @Param("example") BsInventoryUserDepotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_user_depot
     *
     * @mbggenerated Mon May 15 11:54:35 CST 2017
     */
    @UpdateProvider(type=BsInventoryUserDepotSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BsInventoryUserDepot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_user_depot
     *
     * @mbggenerated Mon May 15 11:54:35 CST 2017
     */
    @Update({
        "update bs_inventory_user_depot",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "depot_id = #{depotId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BsInventoryUserDepot record);
}