package lb.rest.user.db.mapper;

import java.util.List;
import lb.rest.user.db.entity.BsInventoryDepot;
import lb.rest.user.db.entity.BsInventoryDepotExample;
import lb.rest.user.db.entity.BsInventoryDepotKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface BsInventoryDepotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_depot
     *
     * @mbggenerated Mon May 15 11:47:33 CST 2017
     */
    @SelectProvider(type=BsInventoryDepotSqlProvider.class, method="countByExample")
    int countByExample(BsInventoryDepotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_depot
     *
     * @mbggenerated Mon May 15 11:47:33 CST 2017
     */
    @DeleteProvider(type=BsInventoryDepotSqlProvider.class, method="deleteByExample")
    int deleteByExample(BsInventoryDepotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_depot
     *
     * @mbggenerated Mon May 15 11:47:33 CST 2017
     */
    @Delete({
        "delete from bs_inventory_depot",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(BsInventoryDepotKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_depot
     *
     * @mbggenerated Mon May 15 11:47:33 CST 2017
     */
    @Insert({
        "insert into bs_inventory_depot (id, owner_id, ",
        "company_id, name, ",
        "address, storage_capacity_str, ",
        "storage_capacity, remark, ",
        "create_time, update_time, ",
        "is_deleted, int_column1, ",
        "int_column2, str_column1, ",
        "str_column2)",
        "values (#{id,jdbcType=INTEGER}, #{ownerId,jdbcType=INTEGER}, ",
        "#{companyId,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR}, #{storageCapacityStr,jdbcType=VARCHAR}, ",
        "#{storageCapacity,jdbcType=DOUBLE}, #{remark,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{isDeleted,jdbcType=INTEGER}, #{intColumn1,jdbcType=INTEGER}, ",
        "#{intColumn2,jdbcType=INTEGER}, #{strColumn1,jdbcType=VARCHAR}, ",
        "#{strColumn2,jdbcType=VARCHAR})"
    })
    int insert(BsInventoryDepot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_depot
     *
     * @mbggenerated Mon May 15 11:47:33 CST 2017
     */
    @InsertProvider(type=BsInventoryDepotSqlProvider.class, method="insertSelective")
    int insertSelective(BsInventoryDepot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_depot
     *
     * @mbggenerated Mon May 15 11:47:33 CST 2017
     */
    @SelectProvider(type=BsInventoryDepotSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="owner_id", property="ownerId", jdbcType=JdbcType.INTEGER),
        @Result(column="company_id", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="storage_capacity_str", property="storageCapacityStr", jdbcType=JdbcType.VARCHAR),
        @Result(column="storage_capacity", property="storageCapacity", jdbcType=JdbcType.DOUBLE),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.INTEGER),
        @Result(column="int_column1", property="intColumn1", jdbcType=JdbcType.INTEGER),
        @Result(column="int_column2", property="intColumn2", jdbcType=JdbcType.INTEGER),
        @Result(column="str_column1", property="strColumn1", jdbcType=JdbcType.VARCHAR),
        @Result(column="str_column2", property="strColumn2", jdbcType=JdbcType.VARCHAR)
    })
    List<BsInventoryDepot> selectByExample(BsInventoryDepotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_depot
     *
     * @mbggenerated Mon May 15 11:47:33 CST 2017
     */
    @Select({
        "select",
        "id, owner_id, company_id, name, address, storage_capacity_str, storage_capacity, ",
        "remark, create_time, update_time, is_deleted, int_column1, int_column2, str_column1, ",
        "str_column2",
        "from bs_inventory_depot",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="owner_id", property="ownerId", jdbcType=JdbcType.INTEGER),
        @Result(column="company_id", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="storage_capacity_str", property="storageCapacityStr", jdbcType=JdbcType.VARCHAR),
        @Result(column="storage_capacity", property="storageCapacity", jdbcType=JdbcType.DOUBLE),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.INTEGER),
        @Result(column="int_column1", property="intColumn1", jdbcType=JdbcType.INTEGER),
        @Result(column="int_column2", property="intColumn2", jdbcType=JdbcType.INTEGER),
        @Result(column="str_column1", property="strColumn1", jdbcType=JdbcType.VARCHAR),
        @Result(column="str_column2", property="strColumn2", jdbcType=JdbcType.VARCHAR)
    })
    BsInventoryDepot selectByPrimaryKey(BsInventoryDepotKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_depot
     *
     * @mbggenerated Mon May 15 11:47:33 CST 2017
     */
    @UpdateProvider(type=BsInventoryDepotSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BsInventoryDepot record, @Param("example") BsInventoryDepotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_depot
     *
     * @mbggenerated Mon May 15 11:47:33 CST 2017
     */
    @UpdateProvider(type=BsInventoryDepotSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BsInventoryDepot record, @Param("example") BsInventoryDepotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_depot
     *
     * @mbggenerated Mon May 15 11:47:33 CST 2017
     */
    @UpdateProvider(type=BsInventoryDepotSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BsInventoryDepot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_inventory_depot
     *
     * @mbggenerated Mon May 15 11:47:33 CST 2017
     */
    @Update({
        "update bs_inventory_depot",
        "set owner_id = #{ownerId,jdbcType=INTEGER},",
          "company_id = #{companyId,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "storage_capacity_str = #{storageCapacityStr,jdbcType=VARCHAR},",
          "storage_capacity = #{storageCapacity,jdbcType=DOUBLE},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "is_deleted = #{isDeleted,jdbcType=INTEGER},",
          "int_column1 = #{intColumn1,jdbcType=INTEGER},",
          "int_column2 = #{intColumn2,jdbcType=INTEGER},",
          "str_column1 = #{strColumn1,jdbcType=VARCHAR},",
          "str_column2 = #{strColumn2,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BsInventoryDepot record);
}