package lb.rest.user.db.mapper;

import java.util.List;
import lb.rest.user.db.entity.BsLeaveWord;
import lb.rest.user.db.entity.BsLeaveWordExample;
import lb.rest.user.db.entity.BsLeaveWordKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface BsLeaveWordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_leave_word
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @SelectProvider(type=BsLeaveWordSqlProvider.class, method="countByExample")
    int countByExample(BsLeaveWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_leave_word
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @DeleteProvider(type=BsLeaveWordSqlProvider.class, method="deleteByExample")
    int deleteByExample(BsLeaveWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_leave_word
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @Delete({
        "delete from bs_leave_word",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(BsLeaveWordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_leave_word
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @Insert({
        "insert into bs_leave_word (id, subject_user_id, ",
        "subject_user_name, object_user_id, ",
        "object_user_name, create_time, ",
        "content, remark, ",
        "view_time, has_read, ",
        "reply_msg, int_column1, ",
        "int_column2, str_column1, ",
        "str_column2)",
        "values (#{id,jdbcType=INTEGER}, #{subjectUserId,jdbcType=INTEGER}, ",
        "#{subjectUserName,jdbcType=VARCHAR}, #{objectUserId,jdbcType=INTEGER}, ",
        "#{objectUserName,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{content,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, ",
        "#{viewTime,jdbcType=TIMESTAMP}, #{hasRead,jdbcType=INTEGER}, ",
        "#{replyMsg,jdbcType=VARCHAR}, #{intColumn1,jdbcType=INTEGER}, ",
        "#{intColumn2,jdbcType=INTEGER}, #{strColumn1,jdbcType=VARCHAR}, ",
        "#{strColumn2,jdbcType=VARCHAR})"
    })
    int insert(BsLeaveWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_leave_word
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @InsertProvider(type=BsLeaveWordSqlProvider.class, method="insertSelective")
    int insertSelective(BsLeaveWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_leave_word
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @SelectProvider(type=BsLeaveWordSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="subject_user_id", property="subjectUserId", jdbcType=JdbcType.INTEGER),
        @Result(column="subject_user_name", property="subjectUserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="object_user_id", property="objectUserId", jdbcType=JdbcType.INTEGER),
        @Result(column="object_user_name", property="objectUserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="view_time", property="viewTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="has_read", property="hasRead", jdbcType=JdbcType.INTEGER),
        @Result(column="reply_msg", property="replyMsg", jdbcType=JdbcType.VARCHAR),
        @Result(column="int_column1", property="intColumn1", jdbcType=JdbcType.INTEGER),
        @Result(column="int_column2", property="intColumn2", jdbcType=JdbcType.INTEGER),
        @Result(column="str_column1", property="strColumn1", jdbcType=JdbcType.VARCHAR),
        @Result(column="str_column2", property="strColumn2", jdbcType=JdbcType.VARCHAR)
    })
    List<BsLeaveWord> selectByExample(BsLeaveWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_leave_word
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @Select({
        "select",
        "id, subject_user_id, subject_user_name, object_user_id, object_user_name, create_time, ",
        "content, remark, view_time, has_read, reply_msg, int_column1, int_column2, str_column1, ",
        "str_column2",
        "from bs_leave_word",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="subject_user_id", property="subjectUserId", jdbcType=JdbcType.INTEGER),
        @Result(column="subject_user_name", property="subjectUserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="object_user_id", property="objectUserId", jdbcType=JdbcType.INTEGER),
        @Result(column="object_user_name", property="objectUserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="view_time", property="viewTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="has_read", property="hasRead", jdbcType=JdbcType.INTEGER),
        @Result(column="reply_msg", property="replyMsg", jdbcType=JdbcType.VARCHAR),
        @Result(column="int_column1", property="intColumn1", jdbcType=JdbcType.INTEGER),
        @Result(column="int_column2", property="intColumn2", jdbcType=JdbcType.INTEGER),
        @Result(column="str_column1", property="strColumn1", jdbcType=JdbcType.VARCHAR),
        @Result(column="str_column2", property="strColumn2", jdbcType=JdbcType.VARCHAR)
    })
    BsLeaveWord selectByPrimaryKey(BsLeaveWordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_leave_word
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @UpdateProvider(type=BsLeaveWordSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BsLeaveWord record, @Param("example") BsLeaveWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_leave_word
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @UpdateProvider(type=BsLeaveWordSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BsLeaveWord record, @Param("example") BsLeaveWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_leave_word
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @UpdateProvider(type=BsLeaveWordSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BsLeaveWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_leave_word
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @Update({
        "update bs_leave_word",
        "set subject_user_id = #{subjectUserId,jdbcType=INTEGER},",
          "subject_user_name = #{subjectUserName,jdbcType=VARCHAR},",
          "object_user_id = #{objectUserId,jdbcType=INTEGER},",
          "object_user_name = #{objectUserName,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "content = #{content,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "view_time = #{viewTime,jdbcType=TIMESTAMP},",
          "has_read = #{hasRead,jdbcType=INTEGER},",
          "reply_msg = #{replyMsg,jdbcType=VARCHAR},",
          "int_column1 = #{intColumn1,jdbcType=INTEGER},",
          "int_column2 = #{intColumn2,jdbcType=INTEGER},",
          "str_column1 = #{strColumn1,jdbcType=VARCHAR},",
          "str_column2 = #{strColumn2,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BsLeaveWord record);
}