package lb.rest.user.db.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import lb.rest.user.db.entity.HtUser;
import lb.rest.user.db.entity.HtUserExample.Criteria;
import lb.rest.user.db.entity.HtUserExample.Criterion;
import lb.rest.user.db.entity.HtUserExample;

public class HtUserSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_user
     *
     * @mbggenerated Fri Feb 24 18:06:20 CST 2017
     */
    public String countByExample(HtUserExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("ht_user");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_user
     *
     * @mbggenerated Fri Feb 24 18:06:20 CST 2017
     */
    public String deleteByExample(HtUserExample example) {
        BEGIN();
        DELETE_FROM("ht_user");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_user
     *
     * @mbggenerated Fri Feb 24 18:06:20 CST 2017
     */
    public String insertSelective(HtUser record) {
        BEGIN();
        INSERT_INTO("ht_user");
        
        if (record.getUserid() != null) {
            VALUES("userId", "#{userid,jdbcType=INTEGER}");
        }
        
        if (record.getUsername() != null) {
            VALUES("userName", "#{username,jdbcType=VARCHAR}");
        }
        
        if (record.getUserpwd() != null) {
            VALUES("userPwd", "#{userpwd,jdbcType=VARCHAR}");
        }
        
        if (record.getUsertype() != null) {
            VALUES("userType", "#{usertype,jdbcType=INTEGER}");
        }
        
        if (record.getRealname() != null) {
            VALUES("realName", "#{realname,jdbcType=VARCHAR}");
        }
        
        if (record.getDepartmentid() != null) {
            VALUES("departmentId", "#{departmentid,jdbcType=INTEGER}");
        }
        
        if (record.getIsavailable() != null) {
            VALUES("isAvailable", "#{isavailable,jdbcType=INTEGER}");
        }
        
        if (record.getCellphone() != null) {
            VALUES("cellphone", "#{cellphone,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            VALUES("email", "#{email,jdbcType=VARCHAR}");
        }
        
        if (record.getCreator() != null) {
            VALUES("creator", "#{creator,jdbcType=INTEGER}");
        }
        
        if (record.getCreatetime() != null) {
            VALUES("createTime", "#{createtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getOpenid() != null) {
            VALUES("openid", "#{openid,jdbcType=VARCHAR}");
        }
        
        if (record.getQyUserId() != null) {
            VALUES("qy_user_id", "#{qyUserId,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_user
     *
     * @mbggenerated Fri Feb 24 18:06:20 CST 2017
     */
    public String selectByExample(HtUserExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("userId");
        } else {
            SELECT("userId");
        }
        SELECT("userName");
        SELECT("userPwd");
        SELECT("userType");
        SELECT("realName");
        SELECT("departmentId");
        SELECT("isAvailable");
        SELECT("cellphone");
        SELECT("email");
        SELECT("creator");
        SELECT("createTime");
        SELECT("openid");
        SELECT("qy_user_id");
        FROM("ht_user");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example != null){
            return SQL().concat(" limit "+example.getOffset()+","+example.getLimit());
        }
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_user
     *
     * @mbggenerated Fri Feb 24 18:06:20 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        HtUser record = (HtUser) parameter.get("record");
        HtUserExample example = (HtUserExample) parameter.get("example");
        
        BEGIN();
        UPDATE("ht_user");
        
        if (record.getUserid() != null) {
            SET("userId = #{record.userid,jdbcType=INTEGER}");
        }
        
        if (record.getUsername() != null) {
            SET("userName = #{record.username,jdbcType=VARCHAR}");
        }
        
        if (record.getUserpwd() != null) {
            SET("userPwd = #{record.userpwd,jdbcType=VARCHAR}");
        }
        
        if (record.getUsertype() != null) {
            SET("userType = #{record.usertype,jdbcType=INTEGER}");
        }
        
        if (record.getRealname() != null) {
            SET("realName = #{record.realname,jdbcType=VARCHAR}");
        }
        
        if (record.getDepartmentid() != null) {
            SET("departmentId = #{record.departmentid,jdbcType=INTEGER}");
        }
        
        if (record.getIsavailable() != null) {
            SET("isAvailable = #{record.isavailable,jdbcType=INTEGER}");
        }
        
        if (record.getCellphone() != null) {
            SET("cellphone = #{record.cellphone,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            SET("email = #{record.email,jdbcType=VARCHAR}");
        }
        
        if (record.getCreator() != null) {
            SET("creator = #{record.creator,jdbcType=INTEGER}");
        }
        
        if (record.getCreatetime() != null) {
            SET("createTime = #{record.createtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getOpenid() != null) {
            SET("openid = #{record.openid,jdbcType=VARCHAR}");
        }
        
        if (record.getQyUserId() != null) {
            SET("qy_user_id = #{record.qyUserId,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_user
     *
     * @mbggenerated Fri Feb 24 18:06:20 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("ht_user");
        
        SET("userId = #{record.userid,jdbcType=INTEGER}");
        SET("userName = #{record.username,jdbcType=VARCHAR}");
        SET("userPwd = #{record.userpwd,jdbcType=VARCHAR}");
        SET("userType = #{record.usertype,jdbcType=INTEGER}");
        SET("realName = #{record.realname,jdbcType=VARCHAR}");
        SET("departmentId = #{record.departmentid,jdbcType=INTEGER}");
        SET("isAvailable = #{record.isavailable,jdbcType=INTEGER}");
        SET("cellphone = #{record.cellphone,jdbcType=VARCHAR}");
        SET("email = #{record.email,jdbcType=VARCHAR}");
        SET("creator = #{record.creator,jdbcType=INTEGER}");
        SET("createTime = #{record.createtime,jdbcType=TIMESTAMP}");
        SET("openid = #{record.openid,jdbcType=VARCHAR}");
        SET("qy_user_id = #{record.qyUserId,jdbcType=VARCHAR}");
        
        HtUserExample example = (HtUserExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_user
     *
     * @mbggenerated Fri Feb 24 18:06:20 CST 2017
     */
    public String updateByPrimaryKeySelective(HtUser record) {
        BEGIN();
        UPDATE("ht_user");
        
        if (record.getUsername() != null) {
            SET("userName = #{username,jdbcType=VARCHAR}");
        }
        
        if (record.getUserpwd() != null) {
            SET("userPwd = #{userpwd,jdbcType=VARCHAR}");
        }
        
        if (record.getUsertype() != null) {
            SET("userType = #{usertype,jdbcType=INTEGER}");
        }
        
        if (record.getRealname() != null) {
            SET("realName = #{realname,jdbcType=VARCHAR}");
        }
        
        if (record.getDepartmentid() != null) {
            SET("departmentId = #{departmentid,jdbcType=INTEGER}");
        }
        
        if (record.getIsavailable() != null) {
            SET("isAvailable = #{isavailable,jdbcType=INTEGER}");
        }
        
        if (record.getCellphone() != null) {
            SET("cellphone = #{cellphone,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            SET("email = #{email,jdbcType=VARCHAR}");
        }
        
        if (record.getCreator() != null) {
            SET("creator = #{creator,jdbcType=INTEGER}");
        }
        
        if (record.getCreatetime() != null) {
            SET("createTime = #{createtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getOpenid() != null) {
            SET("openid = #{openid,jdbcType=VARCHAR}");
        }
        
        if (record.getQyUserId() != null) {
            SET("qy_user_id = #{qyUserId,jdbcType=VARCHAR}");
        }
        
        WHERE("userId = #{userid,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_user
     *
     * @mbggenerated Fri Feb 24 18:06:20 CST 2017
     */
    protected void applyWhere(HtUserExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}