package lb.rest.user.db.mapper;

import java.util.List;

import lb.rest.user.db.entity.MlbRejectionDispose;
import lb.rest.user.db.entity.MlbRejectionDisposeExample;
import lb.rest.user.db.entity.MlbRejectionDisposeKey;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import fc.wpf.rest.db.iface.StaticTableDaoSupport;

public interface MlbRejectionDisposeMapper extends
		StaticTableDaoSupport<MlbRejectionDispose, MlbRejectionDisposeExample, MlbRejectionDisposeKey> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table mlb_rejection_dispose
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	@SelectProvider(type = MlbRejectionDisposeSqlProvider.class, method = "countByExample")
	int countByExample(MlbRejectionDisposeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table mlb_rejection_dispose
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	@DeleteProvider(type = MlbRejectionDisposeSqlProvider.class, method = "deleteByExample")
	int deleteByExample(MlbRejectionDisposeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table mlb_rejection_dispose
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	@Delete({ "delete from mlb_rejection_dispose", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(MlbRejectionDisposeKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table mlb_rejection_dispose
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	@Insert({ "insert into mlb_rejection_dispose (id, user_id, ", "user_name, user_phone, ",
			"apply_time, operation_time, ", "operation_user_id, operation_user_name, ", "location, location_desc, ",
			"address, grain_type, ", "grain_level, quality_desc, ", "price, amount, has_invoice, ",
			"remark, str_column_bak1, ", "int_column_bak1, status)",
			"values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
			"#{userName,jdbcType=VARCHAR}, #{userPhone,jdbcType=VARCHAR}, ",
			"#{applyTime,jdbcType=TIMESTAMP}, #{operationTime,jdbcType=TIMESTAMP}, ",
			"#{operationUserId,jdbcType=INTEGER}, #{operationUserName,jdbcType=VARCHAR}, ",
			"#{location,jdbcType=INTEGER}, #{locationDesc,jdbcType=VARCHAR}, ",
			"#{address,jdbcType=VARCHAR}, #{grainType,jdbcType=INTEGER}, ",
			"#{grainLevel,jdbcType=INTEGER}, #{qualityDesc,jdbcType=VARCHAR}, ",
			"#{price,jdbcType=DOUBLE}, #{amount,jdbcType=DOUBLE}, #{hasInvoice,jdbcType=INTEGER}, ",
			"#{remark,jdbcType=VARCHAR}, #{strColumnBak1,jdbcType=VARCHAR}, ",
			"#{intColumnBak1,jdbcType=INTEGER}, #{status,jdbcType=INTEGER})" })
	int insert(MlbRejectionDispose record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table mlb_rejection_dispose
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	@InsertProvider(type = MlbRejectionDisposeSqlProvider.class, method = "insertSelective")
	int insertSelective(MlbRejectionDispose record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table mlb_rejection_dispose
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	@SelectProvider(type = MlbRejectionDisposeSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "user_id", property = "userId", jdbcType = JdbcType.INTEGER),
			@Result(column = "user_name", property = "userName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "user_phone", property = "userPhone", jdbcType = JdbcType.VARCHAR),
			@Result(column = "apply_time", property = "applyTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "operation_time", property = "operationTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "operation_user_id", property = "operationUserId", jdbcType = JdbcType.INTEGER),
			@Result(column = "operation_user_name", property = "operationUserName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "location", property = "location", jdbcType = JdbcType.INTEGER),
			@Result(column = "location_desc", property = "locationDesc", jdbcType = JdbcType.VARCHAR),
			@Result(column = "address", property = "address", jdbcType = JdbcType.VARCHAR),
			@Result(column = "grain_type", property = "grainType", jdbcType = JdbcType.INTEGER),
			@Result(column = "grain_level", property = "grainLevel", jdbcType = JdbcType.INTEGER),
			@Result(column = "quality_desc", property = "qualityDesc", jdbcType = JdbcType.VARCHAR),
			@Result(column = "price", property = "price", jdbcType = JdbcType.DOUBLE),
			@Result(column = "amount", property = "amount", jdbcType = JdbcType.DOUBLE),
			@Result(column = "has_invoice", property = "hasInvoice", jdbcType = JdbcType.INTEGER),
			@Result(column = "remark", property = "remark", jdbcType = JdbcType.VARCHAR),
			@Result(column = "str_column_bak1", property = "strColumnBak1", jdbcType = JdbcType.VARCHAR),
			@Result(column = "int_column_bak1", property = "intColumnBak1", jdbcType = JdbcType.INTEGER),
			@Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER) })
	List<MlbRejectionDispose> selectByExample(MlbRejectionDisposeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table mlb_rejection_dispose
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	@Select({ "select", "id, user_id, user_name, user_phone, apply_time, operation_time, operation_user_id, ",
			"operation_user_name, location, location_desc, address, grain_type, grain_level, ",
			"quality_desc, price, amount, has_invoice, remark, str_column_bak1, int_column_bak1, ", "status",
			"from mlb_rejection_dispose", "where id = #{id,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "user_id", property = "userId", jdbcType = JdbcType.INTEGER),
			@Result(column = "user_name", property = "userName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "user_phone", property = "userPhone", jdbcType = JdbcType.VARCHAR),
			@Result(column = "apply_time", property = "applyTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "operation_time", property = "operationTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "operation_user_id", property = "operationUserId", jdbcType = JdbcType.INTEGER),
			@Result(column = "operation_user_name", property = "operationUserName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "location", property = "location", jdbcType = JdbcType.INTEGER),
			@Result(column = "location_desc", property = "locationDesc", jdbcType = JdbcType.VARCHAR),
			@Result(column = "address", property = "address", jdbcType = JdbcType.VARCHAR),
			@Result(column = "grain_type", property = "grainType", jdbcType = JdbcType.INTEGER),
			@Result(column = "grain_level", property = "grainLevel", jdbcType = JdbcType.INTEGER),
			@Result(column = "quality_desc", property = "qualityDesc", jdbcType = JdbcType.VARCHAR),
			@Result(column = "price", property = "price", jdbcType = JdbcType.DOUBLE),
			@Result(column = "amount", property = "amount", jdbcType = JdbcType.DOUBLE),
			@Result(column = "has_invoice", property = "hasInvoice", jdbcType = JdbcType.INTEGER),
			@Result(column = "remark", property = "remark", jdbcType = JdbcType.VARCHAR),
			@Result(column = "str_column_bak1", property = "strColumnBak1", jdbcType = JdbcType.VARCHAR),
			@Result(column = "int_column_bak1", property = "intColumnBak1", jdbcType = JdbcType.INTEGER),
			@Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER) })
	MlbRejectionDispose selectByPrimaryKey(MlbRejectionDisposeKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table mlb_rejection_dispose
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	@UpdateProvider(type = MlbRejectionDisposeSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") MlbRejectionDispose record,
			@Param("example") MlbRejectionDisposeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table mlb_rejection_dispose
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	@UpdateProvider(type = MlbRejectionDisposeSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") MlbRejectionDispose record,
			@Param("example") MlbRejectionDisposeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table mlb_rejection_dispose
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	@UpdateProvider(type = MlbRejectionDisposeSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(MlbRejectionDispose record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table mlb_rejection_dispose
	 *
	 * @mbggenerated Tue Mar 07 15:06:55 CST 2017
	 */
	@Update({ "update mlb_rejection_dispose", "set user_id = #{userId,jdbcType=INTEGER},",
			"user_name = #{userName,jdbcType=VARCHAR},", "user_phone = #{userPhone,jdbcType=VARCHAR},",
			"apply_time = #{applyTime,jdbcType=TIMESTAMP},", "operation_time = #{operationTime,jdbcType=TIMESTAMP},",
			"operation_user_id = #{operationUserId,jdbcType=INTEGER},",
			"operation_user_name = #{operationUserName,jdbcType=VARCHAR},", "location = #{location,jdbcType=INTEGER},",
			"location_desc = #{locationDesc,jdbcType=VARCHAR},", "address = #{address,jdbcType=VARCHAR},",
			"grain_type = #{grainType,jdbcType=INTEGER},", "grain_level = #{grainLevel,jdbcType=INTEGER},",
			"quality_desc = #{qualityDesc,jdbcType=VARCHAR},", "price = #{price,jdbcType=DOUBLE},",
			"amount = #{amount,jdbcType=DOUBLE},", "has_invoice = #{hasInvoice,jdbcType=INTEGER},",
			"remark = #{remark,jdbcType=VARCHAR},", "str_column_bak1 = #{strColumnBak1,jdbcType=VARCHAR},",
			"int_column_bak1 = #{intColumnBak1,jdbcType=INTEGER},", "status = #{status,jdbcType=INTEGER}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(MlbRejectionDispose record);
}