package lb.rest.user.db.mapper;

import fc.wpf.rest.db.iface.StaticTableDaoSupport;
import java.util.List;
import lb.rest.user.db.entity.MlbuserAddition;
import lb.rest.user.db.entity.MlbuserAdditionExample;
import lb.rest.user.db.entity.MlbuserAdditionKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MlbuserAdditionMapper extends StaticTableDaoSupport<MlbuserAddition, MlbuserAdditionExample, MlbuserAdditionKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_addition
     *
     * @mbggenerated Sat Feb 25 19:11:45 CST 2017
     */
    @SelectProvider(type=MlbuserAdditionSqlProvider.class, method="countByExample")
    int countByExample(MlbuserAdditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_addition
     *
     * @mbggenerated Sat Feb 25 19:11:45 CST 2017
     */
    @DeleteProvider(type=MlbuserAdditionSqlProvider.class, method="deleteByExample")
    int deleteByExample(MlbuserAdditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_addition
     *
     * @mbggenerated Sat Feb 25 19:11:45 CST 2017
     */
    @Delete({
        "delete from mlbuser_addition",
        "where user_id = #{userId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(MlbuserAdditionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_addition
     *
     * @mbggenerated Sat Feb 25 19:11:45 CST 2017
     */
    @Insert({
        "insert into mlbuser_addition (user_id, user_category, ",
        "has_invoice, has_warehouse, ",
        "company_name, legal_person, ",
        "warename, wareaddress, ",
        "warelocation, warelocationDesc, ",
        "operate_year_limit, month_turnover, ",
        "sale_area, has_tower, ",
        "pay_on_delivery, grain_type, ",
        "buy_address, monthly_require, ",
        "industry, account_period, ",
        "bank_name, bank_user_name, ",
        "bank_account_number, membership_group, ",
        "main_usage, payment_flow, ",
        "quotation_mode, company_location, ",
        "company_locationDesc, company_address)",
        "values (#{userId,jdbcType=INTEGER}, #{userCategory,jdbcType=INTEGER}, ",
        "#{hasInvoice,jdbcType=INTEGER}, #{hasWarehouse,jdbcType=INTEGER}, ",
        "#{companyName,jdbcType=VARCHAR}, #{legalPerson,jdbcType=VARCHAR}, ",
        "#{warename,jdbcType=VARCHAR}, #{wareaddress,jdbcType=VARCHAR}, ",
        "#{warelocation,jdbcType=INTEGER}, #{warelocationdesc,jdbcType=VARCHAR}, ",
        "#{operateYearLimit,jdbcType=INTEGER}, #{monthTurnover,jdbcType=INTEGER}, ",
        "#{saleArea,jdbcType=VARCHAR}, #{hasTower,jdbcType=INTEGER}, ",
        "#{payOnDelivery,jdbcType=INTEGER}, #{grainType,jdbcType=INTEGER}, ",
        "#{buyAddress,jdbcType=VARCHAR}, #{monthlyRequire,jdbcType=INTEGER}, ",
        "#{industry,jdbcType=INTEGER}, #{accountPeriod,jdbcType=INTEGER}, ",
        "#{bankName,jdbcType=VARCHAR}, #{bankUserName,jdbcType=VARCHAR}, ",
        "#{bankAccountNumber,jdbcType=VARCHAR}, #{membershipGroup,jdbcType=VARCHAR}, ",
        "#{mainUsage,jdbcType=VARCHAR}, #{paymentFlow,jdbcType=VARCHAR}, ",
        "#{quotationMode,jdbcType=INTEGER}, #{companyLocation,jdbcType=INTEGER}, ",
        "#{companyLocationdesc,jdbcType=VARCHAR}, #{companyAddress,jdbcType=VARCHAR})"
    })
    int insert(MlbuserAddition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_addition
     *
     * @mbggenerated Sat Feb 25 19:11:45 CST 2017
     */
    @InsertProvider(type=MlbuserAdditionSqlProvider.class, method="insertSelective")
    int insertSelective(MlbuserAddition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_addition
     *
     * @mbggenerated Sat Feb 25 19:11:45 CST 2017
     */
    @SelectProvider(type=MlbuserAdditionSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_category", property="userCategory", jdbcType=JdbcType.INTEGER),
        @Result(column="has_invoice", property="hasInvoice", jdbcType=JdbcType.INTEGER),
        @Result(column="has_warehouse", property="hasWarehouse", jdbcType=JdbcType.INTEGER),
        @Result(column="company_name", property="companyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="legal_person", property="legalPerson", jdbcType=JdbcType.VARCHAR),
        @Result(column="warename", property="warename", jdbcType=JdbcType.VARCHAR),
        @Result(column="wareaddress", property="wareaddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="warelocation", property="warelocation", jdbcType=JdbcType.INTEGER),
        @Result(column="warelocationDesc", property="warelocationdesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="operate_year_limit", property="operateYearLimit", jdbcType=JdbcType.INTEGER),
        @Result(column="month_turnover", property="monthTurnover", jdbcType=JdbcType.INTEGER),
        @Result(column="sale_area", property="saleArea", jdbcType=JdbcType.VARCHAR),
        @Result(column="has_tower", property="hasTower", jdbcType=JdbcType.INTEGER),
        @Result(column="pay_on_delivery", property="payOnDelivery", jdbcType=JdbcType.INTEGER),
        @Result(column="grain_type", property="grainType", jdbcType=JdbcType.INTEGER),
        @Result(column="buy_address", property="buyAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="monthly_require", property="monthlyRequire", jdbcType=JdbcType.INTEGER),
        @Result(column="industry", property="industry", jdbcType=JdbcType.INTEGER),
        @Result(column="account_period", property="accountPeriod", jdbcType=JdbcType.INTEGER),
        @Result(column="bank_name", property="bankName", jdbcType=JdbcType.VARCHAR),
        @Result(column="bank_user_name", property="bankUserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="bank_account_number", property="bankAccountNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="membership_group", property="membershipGroup", jdbcType=JdbcType.VARCHAR),
        @Result(column="main_usage", property="mainUsage", jdbcType=JdbcType.VARCHAR),
        @Result(column="payment_flow", property="paymentFlow", jdbcType=JdbcType.VARCHAR),
        @Result(column="quotation_mode", property="quotationMode", jdbcType=JdbcType.INTEGER),
        @Result(column="company_location", property="companyLocation", jdbcType=JdbcType.INTEGER),
        @Result(column="company_locationDesc", property="companyLocationdesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="company_address", property="companyAddress", jdbcType=JdbcType.VARCHAR)
    })
    List<MlbuserAddition> selectByExample(MlbuserAdditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_addition
     *
     * @mbggenerated Sat Feb 25 19:11:45 CST 2017
     */
    @Select({
        "select",
        "user_id, user_category, has_invoice, has_warehouse, company_name, legal_person, ",
        "warename, wareaddress, warelocation, warelocationDesc, operate_year_limit, month_turnover, ",
        "sale_area, has_tower, pay_on_delivery, grain_type, buy_address, monthly_require, ",
        "industry, account_period, bank_name, bank_user_name, bank_account_number, membership_group, ",
        "main_usage, payment_flow, quotation_mode, company_location, company_locationDesc, ",
        "company_address",
        "from mlbuser_addition",
        "where user_id = #{userId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_category", property="userCategory", jdbcType=JdbcType.INTEGER),
        @Result(column="has_invoice", property="hasInvoice", jdbcType=JdbcType.INTEGER),
        @Result(column="has_warehouse", property="hasWarehouse", jdbcType=JdbcType.INTEGER),
        @Result(column="company_name", property="companyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="legal_person", property="legalPerson", jdbcType=JdbcType.VARCHAR),
        @Result(column="warename", property="warename", jdbcType=JdbcType.VARCHAR),
        @Result(column="wareaddress", property="wareaddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="warelocation", property="warelocation", jdbcType=JdbcType.INTEGER),
        @Result(column="warelocationDesc", property="warelocationdesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="operate_year_limit", property="operateYearLimit", jdbcType=JdbcType.INTEGER),
        @Result(column="month_turnover", property="monthTurnover", jdbcType=JdbcType.INTEGER),
        @Result(column="sale_area", property="saleArea", jdbcType=JdbcType.VARCHAR),
        @Result(column="has_tower", property="hasTower", jdbcType=JdbcType.INTEGER),
        @Result(column="pay_on_delivery", property="payOnDelivery", jdbcType=JdbcType.INTEGER),
        @Result(column="grain_type", property="grainType", jdbcType=JdbcType.INTEGER),
        @Result(column="buy_address", property="buyAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="monthly_require", property="monthlyRequire", jdbcType=JdbcType.INTEGER),
        @Result(column="industry", property="industry", jdbcType=JdbcType.INTEGER),
        @Result(column="account_period", property="accountPeriod", jdbcType=JdbcType.INTEGER),
        @Result(column="bank_name", property="bankName", jdbcType=JdbcType.VARCHAR),
        @Result(column="bank_user_name", property="bankUserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="bank_account_number", property="bankAccountNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="membership_group", property="membershipGroup", jdbcType=JdbcType.VARCHAR),
        @Result(column="main_usage", property="mainUsage", jdbcType=JdbcType.VARCHAR),
        @Result(column="payment_flow", property="paymentFlow", jdbcType=JdbcType.VARCHAR),
        @Result(column="quotation_mode", property="quotationMode", jdbcType=JdbcType.INTEGER),
        @Result(column="company_location", property="companyLocation", jdbcType=JdbcType.INTEGER),
        @Result(column="company_locationDesc", property="companyLocationdesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="company_address", property="companyAddress", jdbcType=JdbcType.VARCHAR)
    })
    MlbuserAddition selectByPrimaryKey(MlbuserAdditionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_addition
     *
     * @mbggenerated Sat Feb 25 19:11:45 CST 2017
     */
    @UpdateProvider(type=MlbuserAdditionSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") MlbuserAddition record, @Param("example") MlbuserAdditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_addition
     *
     * @mbggenerated Sat Feb 25 19:11:45 CST 2017
     */
    @UpdateProvider(type=MlbuserAdditionSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") MlbuserAddition record, @Param("example") MlbuserAdditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_addition
     *
     * @mbggenerated Sat Feb 25 19:11:45 CST 2017
     */
    @UpdateProvider(type=MlbuserAdditionSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MlbuserAddition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_addition
     *
     * @mbggenerated Sat Feb 25 19:11:45 CST 2017
     */
    @Update({
        "update mlbuser_addition",
        "set user_category = #{userCategory,jdbcType=INTEGER},",
          "has_invoice = #{hasInvoice,jdbcType=INTEGER},",
          "has_warehouse = #{hasWarehouse,jdbcType=INTEGER},",
          "company_name = #{companyName,jdbcType=VARCHAR},",
          "legal_person = #{legalPerson,jdbcType=VARCHAR},",
          "warename = #{warename,jdbcType=VARCHAR},",
          "wareaddress = #{wareaddress,jdbcType=VARCHAR},",
          "warelocation = #{warelocation,jdbcType=INTEGER},",
          "warelocationDesc = #{warelocationdesc,jdbcType=VARCHAR},",
          "operate_year_limit = #{operateYearLimit,jdbcType=INTEGER},",
          "month_turnover = #{monthTurnover,jdbcType=INTEGER},",
          "sale_area = #{saleArea,jdbcType=VARCHAR},",
          "has_tower = #{hasTower,jdbcType=INTEGER},",
          "pay_on_delivery = #{payOnDelivery,jdbcType=INTEGER},",
          "grain_type = #{grainType,jdbcType=INTEGER},",
          "buy_address = #{buyAddress,jdbcType=VARCHAR},",
          "monthly_require = #{monthlyRequire,jdbcType=INTEGER},",
          "industry = #{industry,jdbcType=INTEGER},",
          "account_period = #{accountPeriod,jdbcType=INTEGER},",
          "bank_name = #{bankName,jdbcType=VARCHAR},",
          "bank_user_name = #{bankUserName,jdbcType=VARCHAR},",
          "bank_account_number = #{bankAccountNumber,jdbcType=VARCHAR},",
          "membership_group = #{membershipGroup,jdbcType=VARCHAR},",
          "main_usage = #{mainUsage,jdbcType=VARCHAR},",
          "payment_flow = #{paymentFlow,jdbcType=VARCHAR},",
          "quotation_mode = #{quotationMode,jdbcType=INTEGER},",
          "company_location = #{companyLocation,jdbcType=INTEGER},",
          "company_locationDesc = #{companyLocationdesc,jdbcType=VARCHAR},",
          "company_address = #{companyAddress,jdbcType=VARCHAR}",
        "where user_id = #{userId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MlbuserAddition record);
}