package lb.rest.user.db.mapper;

import fc.wpf.rest.db.iface.StaticTableDaoSupport;
import java.util.List;
import lb.rest.user.db.entity.MlbuserApply;
import lb.rest.user.db.entity.MlbuserApplyExample;
import lb.rest.user.db.entity.MlbuserApplyKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MlbuserApplyMapper extends StaticTableDaoSupport<MlbuserApply, MlbuserApplyExample, MlbuserApplyKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_apply
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @SelectProvider(type=MlbuserApplySqlProvider.class, method="countByExample")
    int countByExample(MlbuserApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_apply
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @DeleteProvider(type=MlbuserApplySqlProvider.class, method="deleteByExample")
    int deleteByExample(MlbuserApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_apply
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @Delete({
        "delete from mlbuser_apply",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(MlbuserApplyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_apply
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @Insert({
        "insert into mlbuser_apply (id, mlbuser_id, ",
        "mlbuser_Name, ht_user_id, ",
        "ht_user_name)",
        "values (#{id,jdbcType=INTEGER}, #{mlbuserId,jdbcType=INTEGER}, ",
        "#{mlbuserName,jdbcType=VARCHAR}, #{htUserId,jdbcType=INTEGER}, ",
        "#{htUserName,jdbcType=VARCHAR})"
    })
    int insert(MlbuserApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_apply
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @InsertProvider(type=MlbuserApplySqlProvider.class, method="insertSelective")
    int insertSelective(MlbuserApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_apply
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @SelectProvider(type=MlbuserApplySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="mlbuser_id", property="mlbuserId", jdbcType=JdbcType.INTEGER),
        @Result(column="mlbuser_Name", property="mlbuserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ht_user_id", property="htUserId", jdbcType=JdbcType.INTEGER),
        @Result(column="ht_user_name", property="htUserName", jdbcType=JdbcType.VARCHAR)
    })
    List<MlbuserApply> selectByExample(MlbuserApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_apply
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @Select({
        "select",
        "id, mlbuser_id, mlbuser_Name, ht_user_id, ht_user_name",
        "from mlbuser_apply",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="mlbuser_id", property="mlbuserId", jdbcType=JdbcType.INTEGER),
        @Result(column="mlbuser_Name", property="mlbuserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ht_user_id", property="htUserId", jdbcType=JdbcType.INTEGER),
        @Result(column="ht_user_name", property="htUserName", jdbcType=JdbcType.VARCHAR)
    })
    MlbuserApply selectByPrimaryKey(MlbuserApplyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_apply
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @UpdateProvider(type=MlbuserApplySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") MlbuserApply record, @Param("example") MlbuserApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_apply
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @UpdateProvider(type=MlbuserApplySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") MlbuserApply record, @Param("example") MlbuserApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_apply
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @UpdateProvider(type=MlbuserApplySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MlbuserApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_apply
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @Update({
        "update mlbuser_apply",
        "set mlbuser_id = #{mlbuserId,jdbcType=INTEGER},",
          "mlbuser_Name = #{mlbuserName,jdbcType=VARCHAR},",
          "ht_user_id = #{htUserId,jdbcType=INTEGER},",
          "ht_user_name = #{htUserName,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MlbuserApply record);
}