package lb.rest.user.db.entity;

public class BsUserLevel extends BsUserLevelKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_level.user_id
     *
     * @mbggenerated Fri Jun 09 14:41:01 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_level.user_name
     *
     * @mbggenerated Fri Jun 09 14:41:01 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_level.user_phone
     *
     * @mbggenerated Fri Jun 09 14:41:01 CST 2017
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_level.user_level
     *
     * @mbggenerated Fri Jun 09 14:41:01 CST 2017
     */
    private Integer userLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_level.user_id
     *
     * @return the value of bs_user_level.user_id
     *
     * @mbggenerated Fri Jun 09 14:41:01 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_level.user_id
     *
     * @param userId the value for bs_user_level.user_id
     *
     * @mbggenerated Fri Jun 09 14:41:01 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_level.user_name
     *
     * @return the value of bs_user_level.user_name
     *
     * @mbggenerated Fri Jun 09 14:41:01 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_level.user_name
     *
     * @param userName the value for bs_user_level.user_name
     *
     * @mbggenerated Fri Jun 09 14:41:01 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_level.user_phone
     *
     * @return the value of bs_user_level.user_phone
     *
     * @mbggenerated Fri Jun 09 14:41:01 CST 2017
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_level.user_phone
     *
     * @param userPhone the value for bs_user_level.user_phone
     *
     * @mbggenerated Fri Jun 09 14:41:01 CST 2017
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_level.user_level
     *
     * @return the value of bs_user_level.user_level
     *
     * @mbggenerated Fri Jun 09 14:41:01 CST 2017
     */
    public Integer getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_level.user_level
     *
     * @param userLevel the value for bs_user_level.user_level
     *
     * @mbggenerated Fri Jun 09 14:41:01 CST 2017
     */
    public void setUserLevel(Integer userLevel) {
        this.userLevel = userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user_level
     *
     * @mbggenerated Fri Jun 09 14:41:01 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", userPhone=").append(userPhone);
        sb.append(", userLevel=").append(userLevel);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user_level
     *
     * @mbggenerated Fri Jun 09 14:41:01 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BsUserLevel other = (BsUserLevel) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getUserPhone() == null ? other.getUserPhone() == null : this.getUserPhone().equals(other.getUserPhone()))
            && (this.getUserLevel() == null ? other.getUserLevel() == null : this.getUserLevel().equals(other.getUserLevel()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user_level
     *
     * @mbggenerated Fri Jun 09 14:41:01 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getUserPhone() == null) ? 0 : getUserPhone().hashCode());
        result = prime * result + ((getUserLevel() == null) ? 0 : getUserLevel().hashCode());
        return result;
    }
}