package lb.rest.trade.db.entity;

import fc.wpf.rest.web.bean.Tab;

@Tab(name = "common_attr_value")
public class CommonAttrValue extends CommonAttrValueKey {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column common_attr_value.attrId
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	private Integer attrid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column common_attr_value.attrValue
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	private String attrvalue;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column common_attr_value.typeId
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	private Integer typeid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column common_attr_value.belongId
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	private Integer belongid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column common_attr_value.belongTable
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	private Integer belongtable;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column common_attr_value.attrId
	 *
	 * @return the value of common_attr_value.attrId
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	public Integer getAttrid() {
		return attrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column common_attr_value.attrId
	 *
	 * @param attrid
	 *            the value for common_attr_value.attrId
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	public void setAttrid(Integer attrid) {
		this.attrid = attrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column common_attr_value.attrValue
	 *
	 * @return the value of common_attr_value.attrValue
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	public String getAttrvalue() {
		return attrvalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column common_attr_value.attrValue
	 *
	 * @param attrvalue
	 *            the value for common_attr_value.attrValue
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	public void setAttrvalue(String attrvalue) {
		this.attrvalue = attrvalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column common_attr_value.typeId
	 *
	 * @return the value of common_attr_value.typeId
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	public Integer getTypeid() {
		return typeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column common_attr_value.typeId
	 *
	 * @param typeid
	 *            the value for common_attr_value.typeId
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	public void setTypeid(Integer typeid) {
		this.typeid = typeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column common_attr_value.belongId
	 *
	 * @return the value of common_attr_value.belongId
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	public Integer getBelongid() {
		return belongid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column common_attr_value.belongId
	 *
	 * @param belongid
	 *            the value for common_attr_value.belongId
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	public void setBelongid(Integer belongid) {
		this.belongid = belongid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column common_attr_value.belongTable
	 *
	 * @return the value of common_attr_value.belongTable
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	public Integer getBelongtable() {
		return belongtable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column common_attr_value.belongTable
	 *
	 * @param belongtable
	 *            the value for common_attr_value.belongTable
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	public void setBelongtable(Integer belongtable) {
		this.belongtable = belongtable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table common_attr_value
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		CommonAttrValue other = (CommonAttrValue) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getAttrid() == null ? other.getAttrid() == null : this.getAttrid().equals(other.getAttrid()))
				&& (this.getAttrvalue() == null ? other.getAttrvalue() == null : this.getAttrvalue().equals(
						other.getAttrvalue()))
				&& (this.getTypeid() == null ? other.getTypeid() == null : this.getTypeid().equals(other.getTypeid()))
				&& (this.getBelongid() == null ? other.getBelongid() == null : this.getBelongid().equals(
						other.getBelongid()))
				&& (this.getBelongtable() == null ? other.getBelongtable() == null : this.getBelongtable().equals(
						other.getBelongtable()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table common_attr_value
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getAttrid() == null) ? 0 : getAttrid().hashCode());
		result = prime * result + ((getAttrvalue() == null) ? 0 : getAttrvalue().hashCode());
		result = prime * result + ((getTypeid() == null) ? 0 : getTypeid().hashCode());
		result = prime * result + ((getBelongid() == null) ? 0 : getBelongid().hashCode());
		result = prime * result + ((getBelongtable() == null) ? 0 : getBelongtable().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table common_attr_value
	 *
	 * @mbggenerated Thu Feb 16 17:53:28 CST 2017
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", attrid=").append(attrid);
		sb.append(", attrvalue=").append(attrvalue);
		sb.append(", typeid=").append(typeid);
		sb.append(", belongid=").append(belongid);
		sb.append(", belongtable=").append(belongtable);
		sb.append("]");
		return sb.toString();
	}
}