package lb.rest.trade.db.entity;

import fc.wpf.rest.utils.CustomDateSerializer;
import fc.wpf.rest.web.bean.Tab;
import java.util.Date;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="bs_user_require_match")
public class BsUserRequireMatch extends BsUserRequireMatchKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_require_match.process_status
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    private Integer processStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_require_match.require_id
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    private Long requireId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_require_match.match_goods_id
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    private Integer matchGoodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_require_match.reality_buy_price_type
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    private Integer realityBuyPriceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_require_match.reality_sell_price_type
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    private Integer realitySellPriceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_require_match.reality_buy_price
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    private Double realityBuyPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_require_match.reality_sell_price
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    private Double realitySellPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_require_match.reality_buy_pay_method
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    private Integer realityBuyPayMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_require_match.reality_sell_pay_method
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    private Integer realitySellPayMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_require_match.reality_buy_require
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    private String realityBuyRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_require_match.reality_sell_require
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    private String realitySellRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_require_match.reality_logistics_info
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    private String realityLogisticsInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_require_match.abandon_reason_code
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    private Integer abandonReasonCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_require_match.abandon_reason
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    private String abandonReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_require_match.modify_time
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_user_require_match.complete_time
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    private Date completeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_require_match.process_status
     *
     * @return the value of bs_user_require_match.process_status
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public Integer getProcessStatus() {
        return processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_require_match.process_status
     *
     * @param processStatus the value for bs_user_require_match.process_status
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public void setProcessStatus(Integer processStatus) {
        this.processStatus = processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_require_match.require_id
     *
     * @return the value of bs_user_require_match.require_id
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public Long getRequireId() {
        return requireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_require_match.require_id
     *
     * @param requireId the value for bs_user_require_match.require_id
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public void setRequireId(Long requireId) {
        this.requireId = requireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_require_match.match_goods_id
     *
     * @return the value of bs_user_require_match.match_goods_id
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public Integer getMatchGoodsId() {
        return matchGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_require_match.match_goods_id
     *
     * @param matchGoodsId the value for bs_user_require_match.match_goods_id
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public void setMatchGoodsId(Integer matchGoodsId) {
        this.matchGoodsId = matchGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_require_match.reality_buy_price_type
     *
     * @return the value of bs_user_require_match.reality_buy_price_type
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public Integer getRealityBuyPriceType() {
        return realityBuyPriceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_require_match.reality_buy_price_type
     *
     * @param realityBuyPriceType the value for bs_user_require_match.reality_buy_price_type
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public void setRealityBuyPriceType(Integer realityBuyPriceType) {
        this.realityBuyPriceType = realityBuyPriceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_require_match.reality_sell_price_type
     *
     * @return the value of bs_user_require_match.reality_sell_price_type
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public Integer getRealitySellPriceType() {
        return realitySellPriceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_require_match.reality_sell_price_type
     *
     * @param realitySellPriceType the value for bs_user_require_match.reality_sell_price_type
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public void setRealitySellPriceType(Integer realitySellPriceType) {
        this.realitySellPriceType = realitySellPriceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_require_match.reality_buy_price
     *
     * @return the value of bs_user_require_match.reality_buy_price
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public Double getRealityBuyPrice() {
        return realityBuyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_require_match.reality_buy_price
     *
     * @param realityBuyPrice the value for bs_user_require_match.reality_buy_price
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public void setRealityBuyPrice(Double realityBuyPrice) {
        this.realityBuyPrice = realityBuyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_require_match.reality_sell_price
     *
     * @return the value of bs_user_require_match.reality_sell_price
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public Double getRealitySellPrice() {
        return realitySellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_require_match.reality_sell_price
     *
     * @param realitySellPrice the value for bs_user_require_match.reality_sell_price
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public void setRealitySellPrice(Double realitySellPrice) {
        this.realitySellPrice = realitySellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_require_match.reality_buy_pay_method
     *
     * @return the value of bs_user_require_match.reality_buy_pay_method
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public Integer getRealityBuyPayMethod() {
        return realityBuyPayMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_require_match.reality_buy_pay_method
     *
     * @param realityBuyPayMethod the value for bs_user_require_match.reality_buy_pay_method
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public void setRealityBuyPayMethod(Integer realityBuyPayMethod) {
        this.realityBuyPayMethod = realityBuyPayMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_require_match.reality_sell_pay_method
     *
     * @return the value of bs_user_require_match.reality_sell_pay_method
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public Integer getRealitySellPayMethod() {
        return realitySellPayMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_require_match.reality_sell_pay_method
     *
     * @param realitySellPayMethod the value for bs_user_require_match.reality_sell_pay_method
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public void setRealitySellPayMethod(Integer realitySellPayMethod) {
        this.realitySellPayMethod = realitySellPayMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_require_match.reality_buy_require
     *
     * @return the value of bs_user_require_match.reality_buy_require
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public String getRealityBuyRequire() {
        return realityBuyRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_require_match.reality_buy_require
     *
     * @param realityBuyRequire the value for bs_user_require_match.reality_buy_require
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public void setRealityBuyRequire(String realityBuyRequire) {
        this.realityBuyRequire = realityBuyRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_require_match.reality_sell_require
     *
     * @return the value of bs_user_require_match.reality_sell_require
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public String getRealitySellRequire() {
        return realitySellRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_require_match.reality_sell_require
     *
     * @param realitySellRequire the value for bs_user_require_match.reality_sell_require
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public void setRealitySellRequire(String realitySellRequire) {
        this.realitySellRequire = realitySellRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_require_match.reality_logistics_info
     *
     * @return the value of bs_user_require_match.reality_logistics_info
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public String getRealityLogisticsInfo() {
        return realityLogisticsInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_require_match.reality_logistics_info
     *
     * @param realityLogisticsInfo the value for bs_user_require_match.reality_logistics_info
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public void setRealityLogisticsInfo(String realityLogisticsInfo) {
        this.realityLogisticsInfo = realityLogisticsInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_require_match.abandon_reason_code
     *
     * @return the value of bs_user_require_match.abandon_reason_code
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public Integer getAbandonReasonCode() {
        return abandonReasonCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_require_match.abandon_reason_code
     *
     * @param abandonReasonCode the value for bs_user_require_match.abandon_reason_code
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public void setAbandonReasonCode(Integer abandonReasonCode) {
        this.abandonReasonCode = abandonReasonCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_require_match.abandon_reason
     *
     * @return the value of bs_user_require_match.abandon_reason
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public String getAbandonReason() {
        return abandonReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_require_match.abandon_reason
     *
     * @param abandonReason the value for bs_user_require_match.abandon_reason
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public void setAbandonReason(String abandonReason) {
        this.abandonReason = abandonReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_require_match.modify_time
     *
     * @return the value of bs_user_require_match.modify_time
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_require_match.modify_time
     *
     * @param modifyTime the value for bs_user_require_match.modify_time
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_user_require_match.complete_time
     *
     * @return the value of bs_user_require_match.complete_time
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getCompleteTime() {
        return completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_user_require_match.complete_time
     *
     * @param completeTime the value for bs_user_require_match.complete_time
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    public void setCompleteTime(Date completeTime) {
        this.completeTime = completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user_require_match
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BsUserRequireMatch other = (BsUserRequireMatch) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProcessStatus() == null ? other.getProcessStatus() == null : this.getProcessStatus().equals(other.getProcessStatus()))
            && (this.getRequireId() == null ? other.getRequireId() == null : this.getRequireId().equals(other.getRequireId()))
            && (this.getMatchGoodsId() == null ? other.getMatchGoodsId() == null : this.getMatchGoodsId().equals(other.getMatchGoodsId()))
            && (this.getRealityBuyPriceType() == null ? other.getRealityBuyPriceType() == null : this.getRealityBuyPriceType().equals(other.getRealityBuyPriceType()))
            && (this.getRealitySellPriceType() == null ? other.getRealitySellPriceType() == null : this.getRealitySellPriceType().equals(other.getRealitySellPriceType()))
            && (this.getRealityBuyPrice() == null ? other.getRealityBuyPrice() == null : this.getRealityBuyPrice().equals(other.getRealityBuyPrice()))
            && (this.getRealitySellPrice() == null ? other.getRealitySellPrice() == null : this.getRealitySellPrice().equals(other.getRealitySellPrice()))
            && (this.getRealityBuyPayMethod() == null ? other.getRealityBuyPayMethod() == null : this.getRealityBuyPayMethod().equals(other.getRealityBuyPayMethod()))
            && (this.getRealitySellPayMethod() == null ? other.getRealitySellPayMethod() == null : this.getRealitySellPayMethod().equals(other.getRealitySellPayMethod()))
            && (this.getRealityBuyRequire() == null ? other.getRealityBuyRequire() == null : this.getRealityBuyRequire().equals(other.getRealityBuyRequire()))
            && (this.getRealitySellRequire() == null ? other.getRealitySellRequire() == null : this.getRealitySellRequire().equals(other.getRealitySellRequire()))
            && (this.getRealityLogisticsInfo() == null ? other.getRealityLogisticsInfo() == null : this.getRealityLogisticsInfo().equals(other.getRealityLogisticsInfo()))
            && (this.getAbandonReasonCode() == null ? other.getAbandonReasonCode() == null : this.getAbandonReasonCode().equals(other.getAbandonReasonCode()))
            && (this.getAbandonReason() == null ? other.getAbandonReason() == null : this.getAbandonReason().equals(other.getAbandonReason()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getCompleteTime() == null ? other.getCompleteTime() == null : this.getCompleteTime().equals(other.getCompleteTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user_require_match
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProcessStatus() == null) ? 0 : getProcessStatus().hashCode());
        result = prime * result + ((getRequireId() == null) ? 0 : getRequireId().hashCode());
        result = prime * result + ((getMatchGoodsId() == null) ? 0 : getMatchGoodsId().hashCode());
        result = prime * result + ((getRealityBuyPriceType() == null) ? 0 : getRealityBuyPriceType().hashCode());
        result = prime * result + ((getRealitySellPriceType() == null) ? 0 : getRealitySellPriceType().hashCode());
        result = prime * result + ((getRealityBuyPrice() == null) ? 0 : getRealityBuyPrice().hashCode());
        result = prime * result + ((getRealitySellPrice() == null) ? 0 : getRealitySellPrice().hashCode());
        result = prime * result + ((getRealityBuyPayMethod() == null) ? 0 : getRealityBuyPayMethod().hashCode());
        result = prime * result + ((getRealitySellPayMethod() == null) ? 0 : getRealitySellPayMethod().hashCode());
        result = prime * result + ((getRealityBuyRequire() == null) ? 0 : getRealityBuyRequire().hashCode());
        result = prime * result + ((getRealitySellRequire() == null) ? 0 : getRealitySellRequire().hashCode());
        result = prime * result + ((getRealityLogisticsInfo() == null) ? 0 : getRealityLogisticsInfo().hashCode());
        result = prime * result + ((getAbandonReasonCode() == null) ? 0 : getAbandonReasonCode().hashCode());
        result = prime * result + ((getAbandonReason() == null) ? 0 : getAbandonReason().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getCompleteTime() == null) ? 0 : getCompleteTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_user_require_match
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", processStatus=").append(processStatus);
        sb.append(", requireId=").append(requireId);
        sb.append(", matchGoodsId=").append(matchGoodsId);
        sb.append(", realityBuyPriceType=").append(realityBuyPriceType);
        sb.append(", realitySellPriceType=").append(realitySellPriceType);
        sb.append(", realityBuyPrice=").append(realityBuyPrice);
        sb.append(", realitySellPrice=").append(realitySellPrice);
        sb.append(", realityBuyPayMethod=").append(realityBuyPayMethod);
        sb.append(", realitySellPayMethod=").append(realitySellPayMethod);
        sb.append(", realityBuyRequire=").append(realityBuyRequire);
        sb.append(", realitySellRequire=").append(realitySellRequire);
        sb.append(", realityLogisticsInfo=").append(realityLogisticsInfo);
        sb.append(", abandonReasonCode=").append(abandonReasonCode);
        sb.append(", abandonReason=").append(abandonReason);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", completeTime=").append(completeTime);
        sb.append("]");
        return sb.toString();
    }
}