package lb.rest.user.db.mapper;

import fc.wpf.rest.db.iface.StaticTableDaoSupport;
import java.util.List;
import lb.rest.user.db.entity.MlbuserAuthRecord;
import lb.rest.user.db.entity.MlbuserAuthRecordExample;
import lb.rest.user.db.entity.MlbuserAuthRecordKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MlbuserAuthRecordMapper extends StaticTableDaoSupport<MlbuserAuthRecord, MlbuserAuthRecordExample, MlbuserAuthRecordKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_auth_record
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @SelectProvider(type=MlbuserAuthRecordSqlProvider.class, method="countByExample")
    int countByExample(MlbuserAuthRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_auth_record
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @DeleteProvider(type=MlbuserAuthRecordSqlProvider.class, method="deleteByExample")
    int deleteByExample(MlbuserAuthRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_auth_record
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @Delete({
        "delete from mlbuser_auth_record",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(MlbuserAuthRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_auth_record
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @Insert({
        "insert into mlbuser_auth_record (id, user_id, ",
        "user_name, trade_manager_id, ",
        "trade_manager_name, trade_person_id, ",
        "trade_person_name, client_id, ",
        "client_name, remark, ",
        "create_time, modify_time)",
        "values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{userName,jdbcType=VARCHAR}, #{tradeManagerId,jdbcType=INTEGER}, ",
        "#{tradeManagerName,jdbcType=VARCHAR}, #{tradePersonId,jdbcType=INTEGER}, ",
        "#{tradePersonName,jdbcType=VARCHAR}, #{clientId,jdbcType=INTEGER}, ",
        "#{clientName,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{modifyTime,jdbcType=TIMESTAMP})"
    })
    int insert(MlbuserAuthRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_auth_record
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @InsertProvider(type=MlbuserAuthRecordSqlProvider.class, method="insertSelective")
    int insertSelective(MlbuserAuthRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_auth_record
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @SelectProvider(type=MlbuserAuthRecordSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="trade_manager_id", property="tradeManagerId", jdbcType=JdbcType.INTEGER),
        @Result(column="trade_manager_name", property="tradeManagerName", jdbcType=JdbcType.VARCHAR),
        @Result(column="trade_person_id", property="tradePersonId", jdbcType=JdbcType.INTEGER),
        @Result(column="trade_person_name", property="tradePersonName", jdbcType=JdbcType.VARCHAR),
        @Result(column="client_id", property="clientId", jdbcType=JdbcType.INTEGER),
        @Result(column="client_name", property="clientName", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="modify_time", property="modifyTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<MlbuserAuthRecord> selectByExample(MlbuserAuthRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_auth_record
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @Select({
        "select",
        "id, user_id, user_name, trade_manager_id, trade_manager_name, trade_person_id, ",
        "trade_person_name, client_id, client_name, remark, create_time, modify_time",
        "from mlbuser_auth_record",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="trade_manager_id", property="tradeManagerId", jdbcType=JdbcType.INTEGER),
        @Result(column="trade_manager_name", property="tradeManagerName", jdbcType=JdbcType.VARCHAR),
        @Result(column="trade_person_id", property="tradePersonId", jdbcType=JdbcType.INTEGER),
        @Result(column="trade_person_name", property="tradePersonName", jdbcType=JdbcType.VARCHAR),
        @Result(column="client_id", property="clientId", jdbcType=JdbcType.INTEGER),
        @Result(column="client_name", property="clientName", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="modify_time", property="modifyTime", jdbcType=JdbcType.TIMESTAMP)
    })
    MlbuserAuthRecord selectByPrimaryKey(MlbuserAuthRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_auth_record
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @UpdateProvider(type=MlbuserAuthRecordSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") MlbuserAuthRecord record, @Param("example") MlbuserAuthRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_auth_record
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @UpdateProvider(type=MlbuserAuthRecordSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") MlbuserAuthRecord record, @Param("example") MlbuserAuthRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_auth_record
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @UpdateProvider(type=MlbuserAuthRecordSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MlbuserAuthRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_auth_record
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @Update({
        "update mlbuser_auth_record",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "user_name = #{userName,jdbcType=VARCHAR},",
          "trade_manager_id = #{tradeManagerId,jdbcType=INTEGER},",
          "trade_manager_name = #{tradeManagerName,jdbcType=VARCHAR},",
          "trade_person_id = #{tradePersonId,jdbcType=INTEGER},",
          "trade_person_name = #{tradePersonName,jdbcType=VARCHAR},",
          "client_id = #{clientId,jdbcType=INTEGER},",
          "client_name = #{clientName,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "modify_time = #{modifyTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MlbuserAuthRecord record);
}