package lb.rest.trade.db.entity;

import fc.wpf.rest.utils.CustomDateSerializer;
import fc.wpf.rest.web.bean.Tab;
import java.util.Date;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="bs_reference_price")
public class BsReferencePrice extends BsReferencePriceKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_reference_price.province
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    private Integer province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_reference_price.province_name
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_reference_price.city
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_reference_price.city_name
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_reference_price.food_type
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    private Integer foodType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_reference_price.level
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_reference_price.Price
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_reference_price.Price1
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    private Double price1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_reference_price.unit
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_reference_price.remark
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_reference_price.create_time
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_reference_price.update_time
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_reference_price.create_user_id
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_reference_price.create_user_name
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_reference_price.status
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_reference_price.type
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_reference_price.province
     *
     * @return the value of bs_reference_price.province
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_reference_price.province
     *
     * @param province the value for bs_reference_price.province
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_reference_price.province_name
     *
     * @return the value of bs_reference_price.province_name
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_reference_price.province_name
     *
     * @param provinceName the value for bs_reference_price.province_name
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_reference_price.city
     *
     * @return the value of bs_reference_price.city
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_reference_price.city
     *
     * @param city the value for bs_reference_price.city
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_reference_price.city_name
     *
     * @return the value of bs_reference_price.city_name
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_reference_price.city_name
     *
     * @param cityName the value for bs_reference_price.city_name
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_reference_price.food_type
     *
     * @return the value of bs_reference_price.food_type
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public Integer getFoodType() {
        return foodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_reference_price.food_type
     *
     * @param foodType the value for bs_reference_price.food_type
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public void setFoodType(Integer foodType) {
        this.foodType = foodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_reference_price.level
     *
     * @return the value of bs_reference_price.level
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_reference_price.level
     *
     * @param level the value for bs_reference_price.level
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_reference_price.Price
     *
     * @return the value of bs_reference_price.Price
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_reference_price.Price
     *
     * @param price the value for bs_reference_price.Price
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_reference_price.Price1
     *
     * @return the value of bs_reference_price.Price1
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public Double getPrice1() {
        return price1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_reference_price.Price1
     *
     * @param price1 the value for bs_reference_price.Price1
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public void setPrice1(Double price1) {
        this.price1 = price1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_reference_price.unit
     *
     * @return the value of bs_reference_price.unit
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_reference_price.unit
     *
     * @param unit the value for bs_reference_price.unit
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_reference_price.remark
     *
     * @return the value of bs_reference_price.remark
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_reference_price.remark
     *
     * @param remark the value for bs_reference_price.remark
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_reference_price.create_time
     *
     * @return the value of bs_reference_price.create_time
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_reference_price.create_time
     *
     * @param createTime the value for bs_reference_price.create_time
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_reference_price.update_time
     *
     * @return the value of bs_reference_price.update_time
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_reference_price.update_time
     *
     * @param updateTime the value for bs_reference_price.update_time
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_reference_price.create_user_id
     *
     * @return the value of bs_reference_price.create_user_id
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_reference_price.create_user_id
     *
     * @param createUserId the value for bs_reference_price.create_user_id
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_reference_price.create_user_name
     *
     * @return the value of bs_reference_price.create_user_name
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_reference_price.create_user_name
     *
     * @param createUserName the value for bs_reference_price.create_user_name
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_reference_price.status
     *
     * @return the value of bs_reference_price.status
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_reference_price.status
     *
     * @param status the value for bs_reference_price.status
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_reference_price.type
     *
     * @return the value of bs_reference_price.type
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_reference_price.type
     *
     * @param type the value for bs_reference_price.type
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_reference_price
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BsReferencePrice other = (BsReferencePrice) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getProvinceName() == null ? other.getProvinceName() == null : this.getProvinceName().equals(other.getProvinceName()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getCityName() == null ? other.getCityName() == null : this.getCityName().equals(other.getCityName()))
            && (this.getFoodType() == null ? other.getFoodType() == null : this.getFoodType().equals(other.getFoodType()))
            && (this.getLevel() == null ? other.getLevel() == null : this.getLevel().equals(other.getLevel()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getPrice1() == null ? other.getPrice1() == null : this.getPrice1().equals(other.getPrice1()))
            && (this.getUnit() == null ? other.getUnit() == null : this.getUnit().equals(other.getUnit()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()))
            && (this.getCreateUserName() == null ? other.getCreateUserName() == null : this.getCreateUserName().equals(other.getCreateUserName()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_reference_price
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getProvinceName() == null) ? 0 : getProvinceName().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getCityName() == null) ? 0 : getCityName().hashCode());
        result = prime * result + ((getFoodType() == null) ? 0 : getFoodType().hashCode());
        result = prime * result + ((getLevel() == null) ? 0 : getLevel().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getPrice1() == null) ? 0 : getPrice1().hashCode());
        result = prime * result + ((getUnit() == null) ? 0 : getUnit().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        result = prime * result + ((getCreateUserName() == null) ? 0 : getCreateUserName().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_reference_price
     *
     * @mbggenerated Wed Feb 22 17:20:56 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", province=").append(province);
        sb.append(", provinceName=").append(provinceName);
        sb.append(", city=").append(city);
        sb.append(", cityName=").append(cityName);
        sb.append(", foodType=").append(foodType);
        sb.append(", level=").append(level);
        sb.append(", price=").append(price);
        sb.append(", price1=").append(price1);
        sb.append(", unit=").append(unit);
        sb.append(", remark=").append(remark);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createUserId=").append(createUserId);
        sb.append(", createUserName=").append(createUserName);
        sb.append(", status=").append(status);
        sb.append(", type=").append(type);
        sb.append("]");
        return sb.toString();
    }
}