package lb.rest.trade.db.mapper;

import fc.wpf.rest.db.iface.StaticTableDaoSupport;
import java.util.List;
import lb.rest.trade.db.entity.BsRequireMatch;
import lb.rest.trade.db.entity.BsRequireMatchExample;
import lb.rest.trade.db.entity.BsRequireMatchKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface BsRequireMatchMapper extends StaticTableDaoSupport<BsRequireMatch, BsRequireMatchExample, BsRequireMatchKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_require_match
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    @SelectProvider(type=BsRequireMatchSqlProvider.class, method="countByExample")
    int countByExample(BsRequireMatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_require_match
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    @DeleteProvider(type=BsRequireMatchSqlProvider.class, method="deleteByExample")
    int deleteByExample(BsRequireMatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_require_match
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    @Delete({
        "delete from bs_require_match",
        "where key_id = #{keyId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(BsRequireMatchKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_require_match
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    @Insert({
        "insert into bs_require_match (key_id, require_type, ",
        "require_id, match_id, ",
        "status, operate_user_id, ",
        "opearate_user_name, create_time)",
        "values (#{keyId,jdbcType=INTEGER}, #{requireType,jdbcType=INTEGER}, ",
        "#{requireId,jdbcType=INTEGER}, #{matchId,jdbcType=INTEGER}, ",
        "#{status,jdbcType=INTEGER}, #{operateUserId,jdbcType=INTEGER}, ",
        "#{opearateUserName,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(BsRequireMatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_require_match
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    @InsertProvider(type=BsRequireMatchSqlProvider.class, method="insertSelective")
    int insertSelective(BsRequireMatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_require_match
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    @SelectProvider(type=BsRequireMatchSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="key_id", property="keyId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="require_type", property="requireType", jdbcType=JdbcType.INTEGER),
        @Result(column="require_id", property="requireId", jdbcType=JdbcType.INTEGER),
        @Result(column="match_id", property="matchId", jdbcType=JdbcType.INTEGER),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="operate_user_id", property="operateUserId", jdbcType=JdbcType.INTEGER),
        @Result(column="opearate_user_name", property="opearateUserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<BsRequireMatch> selectByExample(BsRequireMatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_require_match
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    @Select({
        "select",
        "key_id, require_type, require_id, match_id, status, operate_user_id, opearate_user_name, ",
        "create_time",
        "from bs_require_match",
        "where key_id = #{keyId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="key_id", property="keyId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="require_type", property="requireType", jdbcType=JdbcType.INTEGER),
        @Result(column="require_id", property="requireId", jdbcType=JdbcType.INTEGER),
        @Result(column="match_id", property="matchId", jdbcType=JdbcType.INTEGER),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="operate_user_id", property="operateUserId", jdbcType=JdbcType.INTEGER),
        @Result(column="opearate_user_name", property="opearateUserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    BsRequireMatch selectByPrimaryKey(BsRequireMatchKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_require_match
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    @UpdateProvider(type=BsRequireMatchSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BsRequireMatch record, @Param("example") BsRequireMatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_require_match
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    @UpdateProvider(type=BsRequireMatchSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BsRequireMatch record, @Param("example") BsRequireMatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_require_match
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    @UpdateProvider(type=BsRequireMatchSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BsRequireMatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_require_match
     *
     * @mbggenerated Thu Feb 16 18:05:52 CST 2017
     */
    @Update({
        "update bs_require_match",
        "set require_type = #{requireType,jdbcType=INTEGER},",
          "require_id = #{requireId,jdbcType=INTEGER},",
          "match_id = #{matchId,jdbcType=INTEGER},",
          "status = #{status,jdbcType=INTEGER},",
          "operate_user_id = #{operateUserId,jdbcType=INTEGER},",
          "opearate_user_name = #{opearateUserName,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where key_id = #{keyId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BsRequireMatch record);
}