package lb.rest.user.db.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import lb.rest.user.db.entity.BsAdvertPosition;
import lb.rest.user.db.entity.BsAdvertPositionExample.Criteria;
import lb.rest.user.db.entity.BsAdvertPositionExample.Criterion;
import lb.rest.user.db.entity.BsAdvertPositionExample;

public class BsAdvertPositionSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_advert_position
     *
     * @mbggenerated Thu Jul 06 14:40:44 CST 2017
     */
    public String countByExample(BsAdvertPositionExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("bs_advert_position");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_advert_position
     *
     * @mbggenerated Thu Jul 06 14:40:44 CST 2017
     */
    public String deleteByExample(BsAdvertPositionExample example) {
        BEGIN();
        DELETE_FROM("bs_advert_position");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_advert_position
     *
     * @mbggenerated Thu Jul 06 14:40:44 CST 2017
     */
    public String insertSelective(BsAdvertPosition record) {
        BEGIN();
        INSERT_INTO("bs_advert_position");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getAdvertType() != null) {
            VALUES("advert_type", "#{advertType,jdbcType=INTEGER}");
        }
        
        if (record.getTitle() != null) {
            VALUES("title", "#{title,jdbcType=VARCHAR}");
        }
        
        if (record.getContent() != null) {
            VALUES("content", "#{content,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            VALUES("user_id", "#{userId,jdbcType=INTEGER}");
        }
        
        if (record.getUserName() != null) {
            VALUES("user_name", "#{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getUserPhone() != null) {
            VALUES("user_phone", "#{userPhone,jdbcType=VARCHAR}");
        }
        
        if (record.getRank() != null) {
            VALUES("rank", "#{rank,jdbcType=INTEGER}");
        }
        
        if (record.getStatus() != null) {
            VALUES("status", "#{status,jdbcType=INTEGER}");
        }
        
        if (record.getOperateUserId() != null) {
            VALUES("operate_user_id", "#{operateUserId,jdbcType=INTEGER}");
        }
        
        if (record.getOperateUserName() != null) {
            VALUES("operate_user_name", "#{operateUserName,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getIntColumn1() != null) {
            VALUES("int_column1", "#{intColumn1,jdbcType=INTEGER}");
        }
        
        if (record.getIntColumn2() != null) {
            VALUES("int_column2", "#{intColumn2,jdbcType=INTEGER}");
        }
        
        if (record.getStrColumn1() != null) {
            VALUES("str_column1", "#{strColumn1,jdbcType=VARCHAR}");
        }
        
        if (record.getStrColumn2() != null) {
            VALUES("str_column2", "#{strColumn2,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_advert_position
     *
     * @mbggenerated Thu Jul 06 14:40:44 CST 2017
     */
    public String selectByExample(BsAdvertPositionExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("advert_type");
        SELECT("title");
        SELECT("content");
        SELECT("user_id");
        SELECT("user_name");
        SELECT("user_phone");
        SELECT("rank");
        SELECT("status");
        SELECT("operate_user_id");
        SELECT("operate_user_name");
        SELECT("create_time");
        SELECT("update_time");
        SELECT("int_column1");
        SELECT("int_column2");
        SELECT("str_column1");
        SELECT("str_column2");
        FROM("bs_advert_position");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        if (example !=null && example.getLimit() > 0 ) { 
        
        	return SQL() + " limit #{offset,jdbcType=INTEGER} , #{limit,jdbcType=INTEGER}";
        	} 
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_advert_position
     *
     * @mbggenerated Thu Jul 06 14:40:44 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        BsAdvertPosition record = (BsAdvertPosition) parameter.get("record");
        BsAdvertPositionExample example = (BsAdvertPositionExample) parameter.get("example");
        
        BEGIN();
        UPDATE("bs_advert_position");
        
        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getAdvertType() != null) {
            SET("advert_type = #{record.advertType,jdbcType=INTEGER}");
        }
        
        if (record.getTitle() != null) {
            SET("title = #{record.title,jdbcType=VARCHAR}");
        }
        
        if (record.getContent() != null) {
            SET("content = #{record.content,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            SET("user_id = #{record.userId,jdbcType=INTEGER}");
        }
        
        if (record.getUserName() != null) {
            SET("user_name = #{record.userName,jdbcType=VARCHAR}");
        }
        
        if (record.getUserPhone() != null) {
            SET("user_phone = #{record.userPhone,jdbcType=VARCHAR}");
        }
        
        if (record.getRank() != null) {
            SET("rank = #{record.rank,jdbcType=INTEGER}");
        }
        
        if (record.getStatus() != null) {
            SET("status = #{record.status,jdbcType=INTEGER}");
        }
        
        if (record.getOperateUserId() != null) {
            SET("operate_user_id = #{record.operateUserId,jdbcType=INTEGER}");
        }
        
        if (record.getOperateUserName() != null) {
            SET("operate_user_name = #{record.operateUserName,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getIntColumn1() != null) {
            SET("int_column1 = #{record.intColumn1,jdbcType=INTEGER}");
        }
        
        if (record.getIntColumn2() != null) {
            SET("int_column2 = #{record.intColumn2,jdbcType=INTEGER}");
        }
        
        if (record.getStrColumn1() != null) {
            SET("str_column1 = #{record.strColumn1,jdbcType=VARCHAR}");
        }
        
        if (record.getStrColumn2() != null) {
            SET("str_column2 = #{record.strColumn2,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_advert_position
     *
     * @mbggenerated Thu Jul 06 14:40:44 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("bs_advert_position");
        
        SET("id = #{record.id,jdbcType=INTEGER}");
        SET("advert_type = #{record.advertType,jdbcType=INTEGER}");
        SET("title = #{record.title,jdbcType=VARCHAR}");
        SET("content = #{record.content,jdbcType=VARCHAR}");
        SET("user_id = #{record.userId,jdbcType=INTEGER}");
        SET("user_name = #{record.userName,jdbcType=VARCHAR}");
        SET("user_phone = #{record.userPhone,jdbcType=VARCHAR}");
        SET("rank = #{record.rank,jdbcType=INTEGER}");
        SET("status = #{record.status,jdbcType=INTEGER}");
        SET("operate_user_id = #{record.operateUserId,jdbcType=INTEGER}");
        SET("operate_user_name = #{record.operateUserName,jdbcType=VARCHAR}");
        SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        SET("int_column1 = #{record.intColumn1,jdbcType=INTEGER}");
        SET("int_column2 = #{record.intColumn2,jdbcType=INTEGER}");
        SET("str_column1 = #{record.strColumn1,jdbcType=VARCHAR}");
        SET("str_column2 = #{record.strColumn2,jdbcType=VARCHAR}");
        
        BsAdvertPositionExample example = (BsAdvertPositionExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_advert_position
     *
     * @mbggenerated Thu Jul 06 14:40:44 CST 2017
     */
    public String updateByPrimaryKeySelective(BsAdvertPosition record) {
        BEGIN();
        UPDATE("bs_advert_position");
        
        if (record.getAdvertType() != null) {
            SET("advert_type = #{advertType,jdbcType=INTEGER}");
        }
        
        if (record.getTitle() != null) {
            SET("title = #{title,jdbcType=VARCHAR}");
        }
        
        if (record.getContent() != null) {
            SET("content = #{content,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            SET("user_id = #{userId,jdbcType=INTEGER}");
        }
        
        if (record.getUserName() != null) {
            SET("user_name = #{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getUserPhone() != null) {
            SET("user_phone = #{userPhone,jdbcType=VARCHAR}");
        }
        
        if (record.getRank() != null) {
            SET("rank = #{rank,jdbcType=INTEGER}");
        }
        
        if (record.getStatus() != null) {
            SET("status = #{status,jdbcType=INTEGER}");
        }
        
        if (record.getOperateUserId() != null) {
            SET("operate_user_id = #{operateUserId,jdbcType=INTEGER}");
        }
        
        if (record.getOperateUserName() != null) {
            SET("operate_user_name = #{operateUserName,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getIntColumn1() != null) {
            SET("int_column1 = #{intColumn1,jdbcType=INTEGER}");
        }
        
        if (record.getIntColumn2() != null) {
            SET("int_column2 = #{intColumn2,jdbcType=INTEGER}");
        }
        
        if (record.getStrColumn1() != null) {
            SET("str_column1 = #{strColumn1,jdbcType=VARCHAR}");
        }
        
        if (record.getStrColumn2() != null) {
            SET("str_column2 = #{strColumn2,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_advert_position
     *
     * @mbggenerated Thu Jul 06 14:40:44 CST 2017
     */
    protected void applyWhere(BsAdvertPositionExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}