package lb.rest.user.db.mapper;

import java.util.List;
import lb.rest.user.db.entity.BsClickCount;
import lb.rest.user.db.entity.BsClickCountExample;
import lb.rest.user.db.entity.BsClickCountKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface BsClickCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_click_count
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @SelectProvider(type=BsClickCountSqlProvider.class, method="countByExample")
    int countByExample(BsClickCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_click_count
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @DeleteProvider(type=BsClickCountSqlProvider.class, method="deleteByExample")
    int deleteByExample(BsClickCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_click_count
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @Delete({
        "delete from bs_click_count",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(BsClickCountKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_click_count
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @Insert({
        "insert into bs_click_count (id, target_type, ",
        "target_id, target_name, ",
        "operate_time, operate_user_id, ",
        "operate_user_name, operate_type, ",
        "operate_name, content, ",
        "remark, from_type, ",
        "int_column1, int_column2, ",
        "str_column1, str_column2)",
        "values (#{id,jdbcType=INTEGER}, #{targetType,jdbcType=INTEGER}, ",
        "#{targetId,jdbcType=INTEGER}, #{targetName,jdbcType=VARCHAR}, ",
        "#{operateTime,jdbcType=TIMESTAMP}, #{operateUserId,jdbcType=INTEGER}, ",
        "#{operateUserName,jdbcType=VARCHAR}, #{operateType,jdbcType=INTEGER}, ",
        "#{operateName,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR}, #{fromType,jdbcType=INTEGER}, ",
        "#{intColumn1,jdbcType=INTEGER}, #{intColumn2,jdbcType=INTEGER}, ",
        "#{strColumn1,jdbcType=VARCHAR}, #{strColumn2,jdbcType=VARCHAR})"
    })
    int insert(BsClickCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_click_count
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @InsertProvider(type=BsClickCountSqlProvider.class, method="insertSelective")
    int insertSelective(BsClickCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_click_count
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @SelectProvider(type=BsClickCountSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="target_type", property="targetType", jdbcType=JdbcType.INTEGER),
        @Result(column="target_id", property="targetId", jdbcType=JdbcType.INTEGER),
        @Result(column="target_name", property="targetName", jdbcType=JdbcType.VARCHAR),
        @Result(column="operate_time", property="operateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="operate_user_id", property="operateUserId", jdbcType=JdbcType.INTEGER),
        @Result(column="operate_user_name", property="operateUserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="operate_type", property="operateType", jdbcType=JdbcType.INTEGER),
        @Result(column="operate_name", property="operateName", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="from_type", property="fromType", jdbcType=JdbcType.INTEGER),
        @Result(column="int_column1", property="intColumn1", jdbcType=JdbcType.INTEGER),
        @Result(column="int_column2", property="intColumn2", jdbcType=JdbcType.INTEGER),
        @Result(column="str_column1", property="strColumn1", jdbcType=JdbcType.VARCHAR),
        @Result(column="str_column2", property="strColumn2", jdbcType=JdbcType.VARCHAR)
    })
    List<BsClickCount> selectByExample(BsClickCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_click_count
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @Select({
        "select",
        "id, target_type, target_id, target_name, operate_time, operate_user_id, operate_user_name, ",
        "operate_type, operate_name, content, remark, from_type, int_column1, int_column2, ",
        "str_column1, str_column2",
        "from bs_click_count",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="target_type", property="targetType", jdbcType=JdbcType.INTEGER),
        @Result(column="target_id", property="targetId", jdbcType=JdbcType.INTEGER),
        @Result(column="target_name", property="targetName", jdbcType=JdbcType.VARCHAR),
        @Result(column="operate_time", property="operateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="operate_user_id", property="operateUserId", jdbcType=JdbcType.INTEGER),
        @Result(column="operate_user_name", property="operateUserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="operate_type", property="operateType", jdbcType=JdbcType.INTEGER),
        @Result(column="operate_name", property="operateName", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="from_type", property="fromType", jdbcType=JdbcType.INTEGER),
        @Result(column="int_column1", property="intColumn1", jdbcType=JdbcType.INTEGER),
        @Result(column="int_column2", property="intColumn2", jdbcType=JdbcType.INTEGER),
        @Result(column="str_column1", property="strColumn1", jdbcType=JdbcType.VARCHAR),
        @Result(column="str_column2", property="strColumn2", jdbcType=JdbcType.VARCHAR)
    })
    BsClickCount selectByPrimaryKey(BsClickCountKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_click_count
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @UpdateProvider(type=BsClickCountSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BsClickCount record, @Param("example") BsClickCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_click_count
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @UpdateProvider(type=BsClickCountSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BsClickCount record, @Param("example") BsClickCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_click_count
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @UpdateProvider(type=BsClickCountSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BsClickCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_click_count
     *
     * @mbggenerated Thu Jun 01 10:59:28 CST 2017
     */
    @Update({
        "update bs_click_count",
        "set target_type = #{targetType,jdbcType=INTEGER},",
          "target_id = #{targetId,jdbcType=INTEGER},",
          "target_name = #{targetName,jdbcType=VARCHAR},",
          "operate_time = #{operateTime,jdbcType=TIMESTAMP},",
          "operate_user_id = #{operateUserId,jdbcType=INTEGER},",
          "operate_user_name = #{operateUserName,jdbcType=VARCHAR},",
          "operate_type = #{operateType,jdbcType=INTEGER},",
          "operate_name = #{operateName,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "from_type = #{fromType,jdbcType=INTEGER},",
          "int_column1 = #{intColumn1,jdbcType=INTEGER},",
          "int_column2 = #{intColumn2,jdbcType=INTEGER},",
          "str_column1 = #{strColumn1,jdbcType=VARCHAR},",
          "str_column2 = #{strColumn2,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BsClickCount record);
}