package lb.rest.user.db.mapper;

import fc.wpf.rest.db.iface.StaticTableDaoSupport;
import java.util.List;
import lb.rest.user.db.entity.HtUser;
import lb.rest.user.db.entity.HtUserExample;
import lb.rest.user.db.entity.HtUserKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface HtUserMapper extends StaticTableDaoSupport<HtUser, HtUserExample, HtUserKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_user
     *
     * @mbggenerated Fri Feb 24 18:06:20 CST 2017
     */
    @SelectProvider(type=HtUserSqlProvider.class, method="countByExample")
    int countByExample(HtUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_user
     *
     * @mbggenerated Fri Feb 24 18:06:20 CST 2017
     */
    @DeleteProvider(type=HtUserSqlProvider.class, method="deleteByExample")
    int deleteByExample(HtUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_user
     *
     * @mbggenerated Fri Feb 24 18:06:20 CST 2017
     */
    @Delete({
        "delete from ht_user",
        "where userId = #{userid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(HtUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_user
     *
     * @mbggenerated Fri Feb 24 18:06:20 CST 2017
     */
    @Insert({
        "insert into ht_user (userId, userName, ",
        "userPwd, userType, ",
        "realName, departmentId, ",
        "isAvailable, cellphone, ",
        "email, creator, ",
        "createTime, openid, ",
        "qy_user_id)",
        "values (#{userid,jdbcType=INTEGER}, #{username,jdbcType=VARCHAR}, ",
        "#{userpwd,jdbcType=VARCHAR}, #{usertype,jdbcType=INTEGER}, ",
        "#{realname,jdbcType=VARCHAR}, #{departmentid,jdbcType=INTEGER}, ",
        "#{isavailable,jdbcType=INTEGER}, #{cellphone,jdbcType=VARCHAR}, ",
        "#{email,jdbcType=VARCHAR}, #{creator,jdbcType=INTEGER}, ",
        "#{createtime,jdbcType=TIMESTAMP}, #{openid,jdbcType=VARCHAR}, ",
        "#{qyUserId,jdbcType=VARCHAR})"
    })
    int insert(HtUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_user
     *
     * @mbggenerated Fri Feb 24 18:06:20 CST 2017
     */
    @InsertProvider(type=HtUserSqlProvider.class, method="insertSelective")
    int insertSelective(HtUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_user
     *
     * @mbggenerated Fri Feb 24 18:06:20 CST 2017
     */
    @SelectProvider(type=HtUserSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="userId", property="userid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="userName", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="userPwd", property="userpwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="userType", property="usertype", jdbcType=JdbcType.INTEGER),
        @Result(column="realName", property="realname", jdbcType=JdbcType.VARCHAR),
        @Result(column="departmentId", property="departmentid", jdbcType=JdbcType.INTEGER),
        @Result(column="isAvailable", property="isavailable", jdbcType=JdbcType.INTEGER),
        @Result(column="cellphone", property="cellphone", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="creator", property="creator", jdbcType=JdbcType.INTEGER),
        @Result(column="createTime", property="createtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="openid", property="openid", jdbcType=JdbcType.VARCHAR),
        @Result(column="qy_user_id", property="qyUserId", jdbcType=JdbcType.VARCHAR)
    })
    List<HtUser> selectByExample(HtUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_user
     *
     * @mbggenerated Fri Feb 24 18:06:20 CST 2017
     */
    @Select({
        "select",
        "userId, userName, userPwd, userType, realName, departmentId, isAvailable, cellphone, ",
        "email, creator, createTime, openid, qy_user_id",
        "from ht_user",
        "where userId = #{userid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="userId", property="userid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="userName", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="userPwd", property="userpwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="userType", property="usertype", jdbcType=JdbcType.INTEGER),
        @Result(column="realName", property="realname", jdbcType=JdbcType.VARCHAR),
        @Result(column="departmentId", property="departmentid", jdbcType=JdbcType.INTEGER),
        @Result(column="isAvailable", property="isavailable", jdbcType=JdbcType.INTEGER),
        @Result(column="cellphone", property="cellphone", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="creator", property="creator", jdbcType=JdbcType.INTEGER),
        @Result(column="createTime", property="createtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="openid", property="openid", jdbcType=JdbcType.VARCHAR),
        @Result(column="qy_user_id", property="qyUserId", jdbcType=JdbcType.VARCHAR)
    })
    HtUser selectByPrimaryKey(HtUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_user
     *
     * @mbggenerated Fri Feb 24 18:06:20 CST 2017
     */
    @UpdateProvider(type=HtUserSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") HtUser record, @Param("example") HtUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_user
     *
     * @mbggenerated Fri Feb 24 18:06:20 CST 2017
     */
    @UpdateProvider(type=HtUserSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") HtUser record, @Param("example") HtUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_user
     *
     * @mbggenerated Fri Feb 24 18:06:20 CST 2017
     */
    @UpdateProvider(type=HtUserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(HtUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ht_user
     *
     * @mbggenerated Fri Feb 24 18:06:20 CST 2017
     */
    @Update({
        "update ht_user",
        "set userName = #{username,jdbcType=VARCHAR},",
          "userPwd = #{userpwd,jdbcType=VARCHAR},",
          "userType = #{usertype,jdbcType=INTEGER},",
          "realName = #{realname,jdbcType=VARCHAR},",
          "departmentId = #{departmentid,jdbcType=INTEGER},",
          "isAvailable = #{isavailable,jdbcType=INTEGER},",
          "cellphone = #{cellphone,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "creator = #{creator,jdbcType=INTEGER},",
          "createTime = #{createtime,jdbcType=TIMESTAMP},",
          "openid = #{openid,jdbcType=VARCHAR},",
          "qy_user_id = #{qyUserId,jdbcType=VARCHAR}",
        "where userId = #{userid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(HtUser record);
}