package lb.rest.user.db.mapper;

import fc.wpf.rest.db.iface.StaticTableDaoSupport;
import java.util.List;
import lb.rest.user.db.entity.MlbSuggestion;
import lb.rest.user.db.entity.MlbSuggestionExample;
import lb.rest.user.db.entity.MlbSuggestionKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MlbSuggestionMapper extends StaticTableDaoSupport<MlbSuggestion, MlbSuggestionExample, MlbSuggestionKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlb_suggestion
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @SelectProvider(type=MlbSuggestionSqlProvider.class, method="countByExample")
    int countByExample(MlbSuggestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlb_suggestion
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @DeleteProvider(type=MlbSuggestionSqlProvider.class, method="deleteByExample")
    int deleteByExample(MlbSuggestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlb_suggestion
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @Delete({
        "delete from mlb_suggestion",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(MlbSuggestionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlb_suggestion
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @Insert({
        "insert into mlb_suggestion (id, mlbUserId, ",
        "mlbUserName, status, ",
        "suggestion_time, remark, ",
        "deal_time, deal_user, ",
        "reply_msg)",
        "values (#{id,jdbcType=INTEGER}, #{mlbuserid,jdbcType=INTEGER}, ",
        "#{mlbusername,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER}, ",
        "#{suggestionTime,jdbcType=TIMESTAMP}, #{remark,jdbcType=VARCHAR}, ",
        "#{dealTime,jdbcType=TIMESTAMP}, #{dealUser,jdbcType=INTEGER}, ",
        "#{replyMsg,jdbcType=VARCHAR})"
    })
    int insert(MlbSuggestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlb_suggestion
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @InsertProvider(type=MlbSuggestionSqlProvider.class, method="insertSelective")
    int insertSelective(MlbSuggestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlb_suggestion
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @SelectProvider(type=MlbSuggestionSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="mlbUserId", property="mlbuserid", jdbcType=JdbcType.INTEGER),
        @Result(column="mlbUserName", property="mlbusername", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="suggestion_time", property="suggestionTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="deal_time", property="dealTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deal_user", property="dealUser", jdbcType=JdbcType.INTEGER),
        @Result(column="reply_msg", property="replyMsg", jdbcType=JdbcType.VARCHAR)
    })
    List<MlbSuggestion> selectByExample(MlbSuggestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlb_suggestion
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @Select({
        "select",
        "id, mlbUserId, mlbUserName, status, suggestion_time, remark, deal_time, deal_user, ",
        "reply_msg",
        "from mlb_suggestion",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="mlbUserId", property="mlbuserid", jdbcType=JdbcType.INTEGER),
        @Result(column="mlbUserName", property="mlbusername", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="suggestion_time", property="suggestionTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="deal_time", property="dealTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="deal_user", property="dealUser", jdbcType=JdbcType.INTEGER),
        @Result(column="reply_msg", property="replyMsg", jdbcType=JdbcType.VARCHAR)
    })
    MlbSuggestion selectByPrimaryKey(MlbSuggestionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlb_suggestion
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @UpdateProvider(type=MlbSuggestionSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") MlbSuggestion record, @Param("example") MlbSuggestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlb_suggestion
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @UpdateProvider(type=MlbSuggestionSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") MlbSuggestion record, @Param("example") MlbSuggestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlb_suggestion
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @UpdateProvider(type=MlbSuggestionSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MlbSuggestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlb_suggestion
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @Update({
        "update mlb_suggestion",
        "set mlbUserId = #{mlbuserid,jdbcType=INTEGER},",
          "mlbUserName = #{mlbusername,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "suggestion_time = #{suggestionTime,jdbcType=TIMESTAMP},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "deal_time = #{dealTime,jdbcType=TIMESTAMP},",
          "deal_user = #{dealUser,jdbcType=INTEGER},",
          "reply_msg = #{replyMsg,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MlbSuggestion record);
}