package lb.rest.user.db.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import lb.rest.user.db.entity.MlbuserWarehouse;
import lb.rest.user.db.entity.MlbuserWarehouseExample.Criteria;
import lb.rest.user.db.entity.MlbuserWarehouseExample.Criterion;
import lb.rest.user.db.entity.MlbuserWarehouseExample;

public class MlbuserWarehouseSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_warehouse
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public String countByExample(MlbuserWarehouseExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("mlbuser_warehouse");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_warehouse
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public String deleteByExample(MlbuserWarehouseExample example) {
        BEGIN();
        DELETE_FROM("mlbuser_warehouse");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_warehouse
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public String insertSelective(MlbuserWarehouse record) {
        BEGIN();
        INSERT_INTO("mlbuser_warehouse");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            VALUES("user_id", "#{userId,jdbcType=INTEGER}");
        }
        
        if (record.getWarename() != null) {
            VALUES("warename", "#{warename,jdbcType=VARCHAR}");
        }
        
        if (record.getWareaddress() != null) {
            VALUES("wareaddress", "#{wareaddress,jdbcType=VARCHAR}");
        }
        
        if (record.getWarelocation() != null) {
            VALUES("warelocation", "#{warelocation,jdbcType=INTEGER}");
        }
        
        if (record.getWarelocationdesc() != null) {
            VALUES("warelocationDesc", "#{warelocationdesc,jdbcType=VARCHAR}");
        }
        
        if (record.getHasInvoice() != null) {
            VALUES("has_invoice", "#{hasInvoice,jdbcType=INTEGER}");
        }
        
        if (record.getHasTower() != null) {
            VALUES("has_tower", "#{hasTower,jdbcType=INTEGER}");
        }
        
        if (record.getOutPutNum() != null) {
            VALUES("out_put_num", "#{outPutNum,jdbcType=VARCHAR}");
        }
        
        if (record.getFieldScale() != null) {
            VALUES("field_scale", "#{fieldScale,jdbcType=VARCHAR}");
        }
        
        if (record.getYearTurnover() != null) {
            VALUES("year_turnover", "#{yearTurnover,jdbcType=VARCHAR}");
        }
        
        if (record.getMainFlowDirection() != null) {
            VALUES("main_flow_direction", "#{mainFlowDirection,jdbcType=VARCHAR}");
        }
        
        if (record.getOperateYearLimit() != null) {
            VALUES("operate_year_limit", "#{operateYearLimit,jdbcType=VARCHAR}");
        }
        
        if (record.getPropertyRight() != null) {
            VALUES("property_right", "#{propertyRight,jdbcType=VARCHAR}");
        }
        
        if (record.getIsstorage() != null) {
            VALUES("isStorage", "#{isstorage,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_warehouse
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public String selectByExample(MlbuserWarehouseExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("user_id");
        SELECT("warename");
        SELECT("wareaddress");
        SELECT("warelocation");
        SELECT("warelocationDesc");
        SELECT("has_invoice");
        SELECT("has_tower");
        SELECT("out_put_num");
        SELECT("field_scale");
        SELECT("year_turnover");
        SELECT("main_flow_direction");
        SELECT("operate_year_limit");
        SELECT("property_right");
        SELECT("isStorage");
        FROM("mlbuser_warehouse");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example != null){
            return SQL().concat(" limit "+example.getOffset()+","+example.getLimit());
        }
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_warehouse
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        MlbuserWarehouse record = (MlbuserWarehouse) parameter.get("record");
        MlbuserWarehouseExample example = (MlbuserWarehouseExample) parameter.get("example");
        
        BEGIN();
        UPDATE("mlbuser_warehouse");
        
        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            SET("user_id = #{record.userId,jdbcType=INTEGER}");
        }
        
        if (record.getWarename() != null) {
            SET("warename = #{record.warename,jdbcType=VARCHAR}");
        }
        
        if (record.getWareaddress() != null) {
            SET("wareaddress = #{record.wareaddress,jdbcType=VARCHAR}");
        }
        
        if (record.getWarelocation() != null) {
            SET("warelocation = #{record.warelocation,jdbcType=INTEGER}");
        }
        
        if (record.getWarelocationdesc() != null) {
            SET("warelocationDesc = #{record.warelocationdesc,jdbcType=VARCHAR}");
        }
        
        if (record.getHasInvoice() != null) {
            SET("has_invoice = #{record.hasInvoice,jdbcType=INTEGER}");
        }
        
        if (record.getHasTower() != null) {
            SET("has_tower = #{record.hasTower,jdbcType=INTEGER}");
        }
        
        if (record.getOutPutNum() != null) {
            SET("out_put_num = #{record.outPutNum,jdbcType=VARCHAR}");
        }
        
        if (record.getFieldScale() != null) {
            SET("field_scale = #{record.fieldScale,jdbcType=VARCHAR}");
        }
        
        if (record.getYearTurnover() != null) {
            SET("year_turnover = #{record.yearTurnover,jdbcType=VARCHAR}");
        }
        
        if (record.getMainFlowDirection() != null) {
            SET("main_flow_direction = #{record.mainFlowDirection,jdbcType=VARCHAR}");
        }
        
        if (record.getOperateYearLimit() != null) {
            SET("operate_year_limit = #{record.operateYearLimit,jdbcType=VARCHAR}");
        }
        
        if (record.getPropertyRight() != null) {
            SET("property_right = #{record.propertyRight,jdbcType=VARCHAR}");
        }
        
        if (record.getIsstorage() != null) {
            SET("isStorage = #{record.isstorage,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_warehouse
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("mlbuser_warehouse");
        
        SET("id = #{record.id,jdbcType=INTEGER}");
        SET("user_id = #{record.userId,jdbcType=INTEGER}");
        SET("warename = #{record.warename,jdbcType=VARCHAR}");
        SET("wareaddress = #{record.wareaddress,jdbcType=VARCHAR}");
        SET("warelocation = #{record.warelocation,jdbcType=INTEGER}");
        SET("warelocationDesc = #{record.warelocationdesc,jdbcType=VARCHAR}");
        SET("has_invoice = #{record.hasInvoice,jdbcType=INTEGER}");
        SET("has_tower = #{record.hasTower,jdbcType=INTEGER}");
        SET("out_put_num = #{record.outPutNum,jdbcType=VARCHAR}");
        SET("field_scale = #{record.fieldScale,jdbcType=VARCHAR}");
        SET("year_turnover = #{record.yearTurnover,jdbcType=VARCHAR}");
        SET("main_flow_direction = #{record.mainFlowDirection,jdbcType=VARCHAR}");
        SET("operate_year_limit = #{record.operateYearLimit,jdbcType=VARCHAR}");
        SET("property_right = #{record.propertyRight,jdbcType=VARCHAR}");
        SET("isStorage = #{record.isstorage,jdbcType=VARCHAR}");
        
        MlbuserWarehouseExample example = (MlbuserWarehouseExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_warehouse
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public String updateByPrimaryKeySelective(MlbuserWarehouse record) {
        BEGIN();
        UPDATE("mlbuser_warehouse");
        
        if (record.getUserId() != null) {
            SET("user_id = #{userId,jdbcType=INTEGER}");
        }
        
        if (record.getWarename() != null) {
            SET("warename = #{warename,jdbcType=VARCHAR}");
        }
        
        if (record.getWareaddress() != null) {
            SET("wareaddress = #{wareaddress,jdbcType=VARCHAR}");
        }
        
        if (record.getWarelocation() != null) {
            SET("warelocation = #{warelocation,jdbcType=INTEGER}");
        }
        
        if (record.getWarelocationdesc() != null) {
            SET("warelocationDesc = #{warelocationdesc,jdbcType=VARCHAR}");
        }
        
        if (record.getHasInvoice() != null) {
            SET("has_invoice = #{hasInvoice,jdbcType=INTEGER}");
        }
        
        if (record.getHasTower() != null) {
            SET("has_tower = #{hasTower,jdbcType=INTEGER}");
        }
        
        if (record.getOutPutNum() != null) {
            SET("out_put_num = #{outPutNum,jdbcType=VARCHAR}");
        }
        
        if (record.getFieldScale() != null) {
            SET("field_scale = #{fieldScale,jdbcType=VARCHAR}");
        }
        
        if (record.getYearTurnover() != null) {
            SET("year_turnover = #{yearTurnover,jdbcType=VARCHAR}");
        }
        
        if (record.getMainFlowDirection() != null) {
            SET("main_flow_direction = #{mainFlowDirection,jdbcType=VARCHAR}");
        }
        
        if (record.getOperateYearLimit() != null) {
            SET("operate_year_limit = #{operateYearLimit,jdbcType=VARCHAR}");
        }
        
        if (record.getPropertyRight() != null) {
            SET("property_right = #{propertyRight,jdbcType=VARCHAR}");
        }
        
        if (record.getIsstorage() != null) {
            SET("isStorage = #{isstorage,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_warehouse
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    protected void applyWhere(MlbuserWarehouseExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}