package lb.rest.user.db.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;
import lb.rest.user.db.entity.MlbuserApply;
import lb.rest.user.db.entity.MlbuserApplyExample.Criteria;
import lb.rest.user.db.entity.MlbuserApplyExample.Criterion;
import lb.rest.user.db.entity.MlbuserApplyExample;

public class MlbuserApplySqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_apply
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public String countByExample(MlbuserApplyExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("mlbuser_apply");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_apply
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public String deleteByExample(MlbuserApplyExample example) {
        BEGIN();
        DELETE_FROM("mlbuser_apply");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_apply
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public String insertSelective(MlbuserApply record) {
        BEGIN();
        INSERT_INTO("mlbuser_apply");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getMlbuserId() != null) {
            VALUES("mlbuser_id", "#{mlbuserId,jdbcType=INTEGER}");
        }
        
        if (record.getMlbuserName() != null) {
            VALUES("mlbuser_Name", "#{mlbuserName,jdbcType=VARCHAR}");
        }
        
        if (record.getHtUserId() != null) {
            VALUES("ht_user_id", "#{htUserId,jdbcType=INTEGER}");
        }
        
        if (record.getHtUserName() != null) {
            VALUES("ht_user_name", "#{htUserName,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_apply
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public String selectByExample(MlbuserApplyExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("mlbuser_id");
        SELECT("mlbuser_Name");
        SELECT("ht_user_id");
        SELECT("ht_user_name");
        FROM("mlbuser_apply");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example != null){
            return SQL().concat(" limit "+example.getOffset()+","+example.getLimit());
        }
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_apply
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        MlbuserApply record = (MlbuserApply) parameter.get("record");
        MlbuserApplyExample example = (MlbuserApplyExample) parameter.get("example");
        
        BEGIN();
        UPDATE("mlbuser_apply");
        
        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getMlbuserId() != null) {
            SET("mlbuser_id = #{record.mlbuserId,jdbcType=INTEGER}");
        }
        
        if (record.getMlbuserName() != null) {
            SET("mlbuser_Name = #{record.mlbuserName,jdbcType=VARCHAR}");
        }
        
        if (record.getHtUserId() != null) {
            SET("ht_user_id = #{record.htUserId,jdbcType=INTEGER}");
        }
        
        if (record.getHtUserName() != null) {
            SET("ht_user_name = #{record.htUserName,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_apply
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("mlbuser_apply");
        
        SET("id = #{record.id,jdbcType=INTEGER}");
        SET("mlbuser_id = #{record.mlbuserId,jdbcType=INTEGER}");
        SET("mlbuser_Name = #{record.mlbuserName,jdbcType=VARCHAR}");
        SET("ht_user_id = #{record.htUserId,jdbcType=INTEGER}");
        SET("ht_user_name = #{record.htUserName,jdbcType=VARCHAR}");
        
        MlbuserApplyExample example = (MlbuserApplyExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_apply
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    public String updateByPrimaryKeySelective(MlbuserApply record) {
        BEGIN();
        UPDATE("mlbuser_apply");
        
        if (record.getMlbuserId() != null) {
            SET("mlbuser_id = #{mlbuserId,jdbcType=INTEGER}");
        }
        
        if (record.getMlbuserName() != null) {
            SET("mlbuser_Name = #{mlbuserName,jdbcType=VARCHAR}");
        }
        
        if (record.getHtUserId() != null) {
            SET("ht_user_id = #{htUserId,jdbcType=INTEGER}");
        }
        
        if (record.getHtUserName() != null) {
            SET("ht_user_name = #{htUserName,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlbuser_apply
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    protected void applyWhere(MlbuserApplyExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}