package lb.rest.user.db.mapper;

import fc.wpf.rest.db.iface.StaticTableDaoSupport;
import java.util.List;
import lb.rest.user.db.entity.Wxuser;
import lb.rest.user.db.entity.WxuserExample;
import lb.rest.user.db.entity.WxuserKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface WxuserMapper extends StaticTableDaoSupport<Wxuser, WxuserExample, WxuserKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @SelectProvider(type=WxuserSqlProvider.class, method="countByExample")
    int countByExample(WxuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @DeleteProvider(type=WxuserSqlProvider.class, method="deleteByExample")
    int deleteByExample(WxuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @Delete({
        "delete from wxuser",
        "where userid = #{userid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(WxuserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @Insert({
        "insert into wxuser (userid, openid, ",
        "nickname, userimage)",
        "values (#{userid,jdbcType=INTEGER}, #{openid,jdbcType=VARCHAR}, ",
        "#{nickname,jdbcType=VARCHAR}, #{userimage,jdbcType=VARCHAR})"
    })
    int insert(Wxuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @InsertProvider(type=WxuserSqlProvider.class, method="insertSelective")
    int insertSelective(Wxuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @SelectProvider(type=WxuserSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="userid", property="userid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="openid", property="openid", jdbcType=JdbcType.VARCHAR),
        @Result(column="nickname", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="userimage", property="userimage", jdbcType=JdbcType.VARCHAR)
    })
    List<Wxuser> selectByExample(WxuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @Select({
        "select",
        "userid, openid, nickname, userimage",
        "from wxuser",
        "where userid = #{userid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="userid", property="userid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="openid", property="openid", jdbcType=JdbcType.VARCHAR),
        @Result(column="nickname", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="userimage", property="userimage", jdbcType=JdbcType.VARCHAR)
    })
    Wxuser selectByPrimaryKey(WxuserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @UpdateProvider(type=WxuserSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Wxuser record, @Param("example") WxuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @UpdateProvider(type=WxuserSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Wxuser record, @Param("example") WxuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @UpdateProvider(type=WxuserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Wxuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbggenerated Thu Feb 16 17:53:29 CST 2017
     */
    @Update({
        "update wxuser",
        "set openid = #{openid,jdbcType=VARCHAR},",
          "nickname = #{nickname,jdbcType=VARCHAR},",
          "userimage = #{userimage,jdbcType=VARCHAR}",
        "where userid = #{userid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Wxuser record);
}