package lb.rest.trade.db.entity;

import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import fc.wpf.rest.utils.CustomDateSerializer;
import fc.wpf.rest.web.bean.Tab;

@Tab(name = "bs_goods_info")
public class BsGoodsInfo extends BsGoodsInfoKey {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.process_status
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Integer processStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.check_service_status
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Integer checkServiceStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.service_type
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Integer serviceType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.user_id
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.user_name
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private String userName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.address
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.user_phone
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private String userPhone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.food_type
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Integer foodType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.food_price
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Double foodPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.food_num
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Double foodNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.food_require
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private String foodRequire;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.location
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Integer location;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.location_desc
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private String locationDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.check_status
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Integer checkStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.check_user_id
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Integer checkUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.check_user_name
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private String checkUserName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.check_user_time
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Date checkUserTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.food_source
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private String foodSource;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.has_invoice
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Integer hasInvoice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.price_type
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Integer priceType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.pay_method
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Integer payMethod;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.abandon_reason_code
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Integer abandonReasonCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.abandon_reason
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private String abandonReason;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.remark
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private String remark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.operate_user_id
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Integer operateUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.opearate_user_name
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private String opearateUserName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.view_count
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Integer viewCount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.create_time
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.modify_time
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Date modifyTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.auth_status
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Integer authStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.has_logistics
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Integer hasLogistics;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.grain_level
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Integer grainLevel;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.category
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Integer category;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.create_userid
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private Integer createUserid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.create_username
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private String createUsername;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.column1
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private String column1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bs_goods_info.column2
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	private String column2;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.process_status
	 *
	 * @return the value of bs_goods_info.process_status
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public Integer getProcessStatus() {
		return processStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.process_status
	 *
	 * @param processStatus
	 *            the value for bs_goods_info.process_status
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setProcessStatus(Integer processStatus) {
		this.processStatus = processStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.check_service_status
	 *
	 * @return the value of bs_goods_info.check_service_status
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public Integer getCheckServiceStatus() {
		return checkServiceStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.check_service_status
	 *
	 * @param checkServiceStatus
	 *            the value for bs_goods_info.check_service_status
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setCheckServiceStatus(Integer checkServiceStatus) {
		this.checkServiceStatus = checkServiceStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.service_type
	 *
	 * @return the value of bs_goods_info.service_type
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public Integer getServiceType() {
		return serviceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.service_type
	 *
	 * @param serviceType
	 *            the value for bs_goods_info.service_type
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setServiceType(Integer serviceType) {
		this.serviceType = serviceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.user_id
	 *
	 * @return the value of bs_goods_info.user_id
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.user_id
	 *
	 * @param userId
	 *            the value for bs_goods_info.user_id
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.user_name
	 *
	 * @return the value of bs_goods_info.user_name
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.user_name
	 *
	 * @param userName
	 *            the value for bs_goods_info.user_name
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.address
	 *
	 * @return the value of bs_goods_info.address
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.address
	 *
	 * @param address
	 *            the value for bs_goods_info.address
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.user_phone
	 *
	 * @return the value of bs_goods_info.user_phone
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public String getUserPhone() {
		return userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.user_phone
	 *
	 * @param userPhone
	 *            the value for bs_goods_info.user_phone
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.food_type
	 *
	 * @return the value of bs_goods_info.food_type
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public Integer getFoodType() {
		return foodType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.food_type
	 *
	 * @param foodType
	 *            the value for bs_goods_info.food_type
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setFoodType(Integer foodType) {
		this.foodType = foodType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.food_price
	 *
	 * @return the value of bs_goods_info.food_price
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public Double getFoodPrice() {
		return foodPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.food_price
	 *
	 * @param foodPrice
	 *            the value for bs_goods_info.food_price
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setFoodPrice(Double foodPrice) {
		this.foodPrice = foodPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.food_num
	 *
	 * @return the value of bs_goods_info.food_num
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public Double getFoodNum() {
		return foodNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.food_num
	 *
	 * @param foodNum
	 *            the value for bs_goods_info.food_num
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setFoodNum(Double foodNum) {
		this.foodNum = foodNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.food_require
	 *
	 * @return the value of bs_goods_info.food_require
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public String getFoodRequire() {
		return foodRequire;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.food_require
	 *
	 * @param foodRequire
	 *            the value for bs_goods_info.food_require
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setFoodRequire(String foodRequire) {
		this.foodRequire = foodRequire;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.location
	 *
	 * @return the value of bs_goods_info.location
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public Integer getLocation() {
		return location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.location
	 *
	 * @param location
	 *            the value for bs_goods_info.location
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setLocation(Integer location) {
		this.location = location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.location_desc
	 *
	 * @return the value of bs_goods_info.location_desc
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public String getLocationDesc() {
		return locationDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.location_desc
	 *
	 * @param locationDesc
	 *            the value for bs_goods_info.location_desc
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setLocationDesc(String locationDesc) {
		this.locationDesc = locationDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.check_status
	 *
	 * @return the value of bs_goods_info.check_status
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public Integer getCheckStatus() {
		return checkStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.check_status
	 *
	 * @param checkStatus
	 *            the value for bs_goods_info.check_status
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setCheckStatus(Integer checkStatus) {
		this.checkStatus = checkStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.check_user_id
	 *
	 * @return the value of bs_goods_info.check_user_id
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public Integer getCheckUserId() {
		return checkUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.check_user_id
	 *
	 * @param checkUserId
	 *            the value for bs_goods_info.check_user_id
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setCheckUserId(Integer checkUserId) {
		this.checkUserId = checkUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.check_user_name
	 *
	 * @return the value of bs_goods_info.check_user_name
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public String getCheckUserName() {
		return checkUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.check_user_name
	 *
	 * @param checkUserName
	 *            the value for bs_goods_info.check_user_name
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setCheckUserName(String checkUserName) {
		this.checkUserName = checkUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.check_user_time
	 *
	 * @return the value of bs_goods_info.check_user_time
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	@JsonSerialize(using = CustomDateSerializer.class)
	public Date getCheckUserTime() {
		return checkUserTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.check_user_time
	 *
	 * @param checkUserTime
	 *            the value for bs_goods_info.check_user_time
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setCheckUserTime(Date checkUserTime) {
		this.checkUserTime = checkUserTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.food_source
	 *
	 * @return the value of bs_goods_info.food_source
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public String getFoodSource() {
		return foodSource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.food_source
	 *
	 * @param foodSource
	 *            the value for bs_goods_info.food_source
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setFoodSource(String foodSource) {
		this.foodSource = foodSource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.has_invoice
	 *
	 * @return the value of bs_goods_info.has_invoice
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public Integer getHasInvoice() {
		return hasInvoice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.has_invoice
	 *
	 * @param hasInvoice
	 *            the value for bs_goods_info.has_invoice
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setHasInvoice(Integer hasInvoice) {
		this.hasInvoice = hasInvoice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.price_type
	 *
	 * @return the value of bs_goods_info.price_type
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public Integer getPriceType() {
		return priceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.price_type
	 *
	 * @param priceType
	 *            the value for bs_goods_info.price_type
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setPriceType(Integer priceType) {
		this.priceType = priceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.pay_method
	 *
	 * @return the value of bs_goods_info.pay_method
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public Integer getPayMethod() {
		return payMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.pay_method
	 *
	 * @param payMethod
	 *            the value for bs_goods_info.pay_method
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setPayMethod(Integer payMethod) {
		this.payMethod = payMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.abandon_reason_code
	 *
	 * @return the value of bs_goods_info.abandon_reason_code
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public Integer getAbandonReasonCode() {
		return abandonReasonCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.abandon_reason_code
	 *
	 * @param abandonReasonCode
	 *            the value for bs_goods_info.abandon_reason_code
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setAbandonReasonCode(Integer abandonReasonCode) {
		this.abandonReasonCode = abandonReasonCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.abandon_reason
	 *
	 * @return the value of bs_goods_info.abandon_reason
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public String getAbandonReason() {
		return abandonReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.abandon_reason
	 *
	 * @param abandonReason
	 *            the value for bs_goods_info.abandon_reason
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setAbandonReason(String abandonReason) {
		this.abandonReason = abandonReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.remark
	 *
	 * @return the value of bs_goods_info.remark
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.remark
	 *
	 * @param remark
	 *            the value for bs_goods_info.remark
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.operate_user_id
	 *
	 * @return the value of bs_goods_info.operate_user_id
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public Integer getOperateUserId() {
		return operateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.operate_user_id
	 *
	 * @param operateUserId
	 *            the value for bs_goods_info.operate_user_id
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setOperateUserId(Integer operateUserId) {
		this.operateUserId = operateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.opearate_user_name
	 *
	 * @return the value of bs_goods_info.opearate_user_name
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public String getOpearateUserName() {
		return opearateUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.opearate_user_name
	 *
	 * @param opearateUserName
	 *            the value for bs_goods_info.opearate_user_name
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setOpearateUserName(String opearateUserName) {
		this.opearateUserName = opearateUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.view_count
	 *
	 * @return the value of bs_goods_info.view_count
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public Integer getViewCount() {
		return viewCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.view_count
	 *
	 * @param viewCount
	 *            the value for bs_goods_info.view_count
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setViewCount(Integer viewCount) {
		this.viewCount = viewCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.create_time
	 *
	 * @return the value of bs_goods_info.create_time
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	@JsonSerialize(using = CustomDateSerializer.class)
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.create_time
	 *
	 * @param createTime
	 *            the value for bs_goods_info.create_time
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.modify_time
	 *
	 * @return the value of bs_goods_info.modify_time
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	@JsonSerialize(using = CustomDateSerializer.class)
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.modify_time
	 *
	 * @param modifyTime
	 *            the value for bs_goods_info.modify_time
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.auth_status
	 *
	 * @return the value of bs_goods_info.auth_status
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public Integer getAuthStatus() {
		return authStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.auth_status
	 *
	 * @param authStatus
	 *            the value for bs_goods_info.auth_status
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setAuthStatus(Integer authStatus) {
		this.authStatus = authStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.has_logistics
	 *
	 * @return the value of bs_goods_info.has_logistics
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public Integer getHasLogistics() {
		return hasLogistics;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.has_logistics
	 *
	 * @param hasLogistics
	 *            the value for bs_goods_info.has_logistics
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setHasLogistics(Integer hasLogistics) {
		this.hasLogistics = hasLogistics;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.grain_level
	 *
	 * @return the value of bs_goods_info.grain_level
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public Integer getGrainLevel() {
		return grainLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.grain_level
	 *
	 * @param grainLevel
	 *            the value for bs_goods_info.grain_level
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setGrainLevel(Integer grainLevel) {
		this.grainLevel = grainLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.category
	 *
	 * @return the value of bs_goods_info.category
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public Integer getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.category
	 *
	 * @param category
	 *            the value for bs_goods_info.category
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setCategory(Integer category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.create_userid
	 *
	 * @return the value of bs_goods_info.create_userid
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public Integer getCreateUserid() {
		return createUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.create_userid
	 *
	 * @param createUserid
	 *            the value for bs_goods_info.create_userid
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setCreateUserid(Integer createUserid) {
		this.createUserid = createUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.create_username
	 *
	 * @return the value of bs_goods_info.create_username
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public String getCreateUsername() {
		return createUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.create_username
	 *
	 * @param createUsername
	 *            the value for bs_goods_info.create_username
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setCreateUsername(String createUsername) {
		this.createUsername = createUsername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.column1
	 *
	 * @return the value of bs_goods_info.column1
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public String getColumn1() {
		return column1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.column1
	 *
	 * @param column1
	 *            the value for bs_goods_info.column1
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setColumn1(String column1) {
		this.column1 = column1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bs_goods_info.column2
	 *
	 * @return the value of bs_goods_info.column2
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public String getColumn2() {
		return column2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bs_goods_info.column2
	 *
	 * @param column2
	 *            the value for bs_goods_info.column2
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	public void setColumn2(String column2) {
		this.column2 = column2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bs_goods_info
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		BsGoodsInfo other = (BsGoodsInfo) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getProcessStatus() == null ? other.getProcessStatus() == null : this.getProcessStatus()
						.equals(other.getProcessStatus()))
				&& (this.getCheckServiceStatus() == null ? other.getCheckServiceStatus() == null : this
						.getCheckServiceStatus().equals(other.getCheckServiceStatus()))
				&& (this.getServiceType() == null ? other.getServiceType() == null : this.getServiceType().equals(
						other.getServiceType()))
				&& (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
				&& (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(
						other.getUserName()))
				&& (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(
						other.getAddress()))
				&& (this.getUserPhone() == null ? other.getUserPhone() == null : this.getUserPhone().equals(
						other.getUserPhone()))
				&& (this.getFoodType() == null ? other.getFoodType() == null : this.getFoodType().equals(
						other.getFoodType()))
				&& (this.getFoodPrice() == null ? other.getFoodPrice() == null : this.getFoodPrice().equals(
						other.getFoodPrice()))
				&& (this.getFoodNum() == null ? other.getFoodNum() == null : this.getFoodNum().equals(
						other.getFoodNum()))
				&& (this.getFoodRequire() == null ? other.getFoodRequire() == null : this.getFoodRequire().equals(
						other.getFoodRequire()))
				&& (this.getLocation() == null ? other.getLocation() == null : this.getLocation().equals(
						other.getLocation()))
				&& (this.getLocationDesc() == null ? other.getLocationDesc() == null : this.getLocationDesc().equals(
						other.getLocationDesc()))
				&& (this.getCheckStatus() == null ? other.getCheckStatus() == null : this.getCheckStatus().equals(
						other.getCheckStatus()))
				&& (this.getCheckUserId() == null ? other.getCheckUserId() == null : this.getCheckUserId().equals(
						other.getCheckUserId()))
				&& (this.getCheckUserName() == null ? other.getCheckUserName() == null : this.getCheckUserName()
						.equals(other.getCheckUserName()))
				&& (this.getCheckUserTime() == null ? other.getCheckUserTime() == null : this.getCheckUserTime()
						.equals(other.getCheckUserTime()))
				&& (this.getFoodSource() == null ? other.getFoodSource() == null : this.getFoodSource().equals(
						other.getFoodSource()))
				&& (this.getHasInvoice() == null ? other.getHasInvoice() == null : this.getHasInvoice().equals(
						other.getHasInvoice()))
				&& (this.getPriceType() == null ? other.getPriceType() == null : this.getPriceType().equals(
						other.getPriceType()))
				&& (this.getPayMethod() == null ? other.getPayMethod() == null : this.getPayMethod().equals(
						other.getPayMethod()))
				&& (this.getAbandonReasonCode() == null ? other.getAbandonReasonCode() == null : this
						.getAbandonReasonCode().equals(other.getAbandonReasonCode()))
				&& (this.getAbandonReason() == null ? other.getAbandonReason() == null : this.getAbandonReason()
						.equals(other.getAbandonReason()))
				&& (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
				&& (this.getOperateUserId() == null ? other.getOperateUserId() == null : this.getOperateUserId()
						.equals(other.getOperateUserId()))
				&& (this.getOpearateUserName() == null ? other.getOpearateUserName() == null : this
						.getOpearateUserName().equals(other.getOpearateUserName()))
				&& (this.getViewCount() == null ? other.getViewCount() == null : this.getViewCount().equals(
						other.getViewCount()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(
						other.getCreateTime()))
				&& (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(
						other.getModifyTime()))
				&& (this.getAuthStatus() == null ? other.getAuthStatus() == null : this.getAuthStatus().equals(
						other.getAuthStatus()))
				&& (this.getHasLogistics() == null ? other.getHasLogistics() == null : this.getHasLogistics().equals(
						other.getHasLogistics()))
				&& (this.getGrainLevel() == null ? other.getGrainLevel() == null : this.getGrainLevel().equals(
						other.getGrainLevel()))
				&& (this.getCategory() == null ? other.getCategory() == null : this.getCategory().equals(
						other.getCategory()))
				&& (this.getCreateUserid() == null ? other.getCreateUserid() == null : this.getCreateUserid().equals(
						other.getCreateUserid()))
				&& (this.getCreateUsername() == null ? other.getCreateUsername() == null : this.getCreateUsername()
						.equals(other.getCreateUsername()))
				&& (this.getColumn1() == null ? other.getColumn1() == null : this.getColumn1().equals(
						other.getColumn1()))
				&& (this.getColumn2() == null ? other.getColumn2() == null : this.getColumn2().equals(
						other.getColumn2()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bs_goods_info
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getProcessStatus() == null) ? 0 : getProcessStatus().hashCode());
		result = prime * result + ((getCheckServiceStatus() == null) ? 0 : getCheckServiceStatus().hashCode());
		result = prime * result + ((getServiceType() == null) ? 0 : getServiceType().hashCode());
		result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
		result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
		result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
		result = prime * result + ((getUserPhone() == null) ? 0 : getUserPhone().hashCode());
		result = prime * result + ((getFoodType() == null) ? 0 : getFoodType().hashCode());
		result = prime * result + ((getFoodPrice() == null) ? 0 : getFoodPrice().hashCode());
		result = prime * result + ((getFoodNum() == null) ? 0 : getFoodNum().hashCode());
		result = prime * result + ((getFoodRequire() == null) ? 0 : getFoodRequire().hashCode());
		result = prime * result + ((getLocation() == null) ? 0 : getLocation().hashCode());
		result = prime * result + ((getLocationDesc() == null) ? 0 : getLocationDesc().hashCode());
		result = prime * result + ((getCheckStatus() == null) ? 0 : getCheckStatus().hashCode());
		result = prime * result + ((getCheckUserId() == null) ? 0 : getCheckUserId().hashCode());
		result = prime * result + ((getCheckUserName() == null) ? 0 : getCheckUserName().hashCode());
		result = prime * result + ((getCheckUserTime() == null) ? 0 : getCheckUserTime().hashCode());
		result = prime * result + ((getFoodSource() == null) ? 0 : getFoodSource().hashCode());
		result = prime * result + ((getHasInvoice() == null) ? 0 : getHasInvoice().hashCode());
		result = prime * result + ((getPriceType() == null) ? 0 : getPriceType().hashCode());
		result = prime * result + ((getPayMethod() == null) ? 0 : getPayMethod().hashCode());
		result = prime * result + ((getAbandonReasonCode() == null) ? 0 : getAbandonReasonCode().hashCode());
		result = prime * result + ((getAbandonReason() == null) ? 0 : getAbandonReason().hashCode());
		result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
		result = prime * result + ((getOperateUserId() == null) ? 0 : getOperateUserId().hashCode());
		result = prime * result + ((getOpearateUserName() == null) ? 0 : getOpearateUserName().hashCode());
		result = prime * result + ((getViewCount() == null) ? 0 : getViewCount().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
		result = prime * result + ((getAuthStatus() == null) ? 0 : getAuthStatus().hashCode());
		result = prime * result + ((getHasLogistics() == null) ? 0 : getHasLogistics().hashCode());
		result = prime * result + ((getGrainLevel() == null) ? 0 : getGrainLevel().hashCode());
		result = prime * result + ((getCategory() == null) ? 0 : getCategory().hashCode());
		result = prime * result + ((getCreateUserid() == null) ? 0 : getCreateUserid().hashCode());
		result = prime * result + ((getCreateUsername() == null) ? 0 : getCreateUsername().hashCode());
		result = prime * result + ((getColumn1() == null) ? 0 : getColumn1().hashCode());
		result = prime * result + ((getColumn2() == null) ? 0 : getColumn2().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bs_goods_info
	 *
	 * @mbggenerated Fri Feb 24 18:06:23 CST 2017
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", processStatus=").append(processStatus);
		sb.append(", checkServiceStatus=").append(checkServiceStatus);
		sb.append(", serviceType=").append(serviceType);
		sb.append(", userId=").append(userId);
		sb.append(", userName=").append(userName);
		sb.append(", address=").append(address);
		sb.append(", userPhone=").append(userPhone);
		sb.append(", foodType=").append(foodType);
		sb.append(", foodPrice=").append(foodPrice);
		sb.append(", foodNum=").append(foodNum);
		sb.append(", foodRequire=").append(foodRequire);
		sb.append(", location=").append(location);
		sb.append(", locationDesc=").append(locationDesc);
		sb.append(", checkStatus=").append(checkStatus);
		sb.append(", checkUserId=").append(checkUserId);
		sb.append(", checkUserName=").append(checkUserName);
		sb.append(", checkUserTime=").append(checkUserTime);
		sb.append(", foodSource=").append(foodSource);
		sb.append(", hasInvoice=").append(hasInvoice);
		sb.append(", priceType=").append(priceType);
		sb.append(", payMethod=").append(payMethod);
		sb.append(", abandonReasonCode=").append(abandonReasonCode);
		sb.append(", abandonReason=").append(abandonReason);
		sb.append(", remark=").append(remark);
		sb.append(", operateUserId=").append(operateUserId);
		sb.append(", opearateUserName=").append(opearateUserName);
		sb.append(", viewCount=").append(viewCount);
		sb.append(", createTime=").append(createTime);
		sb.append(", modifyTime=").append(modifyTime);
		sb.append(", authStatus=").append(authStatus);
		sb.append(", hasLogistics=").append(hasLogistics);
		sb.append(", grainLevel=").append(grainLevel);
		sb.append(", category=").append(category);
		sb.append(", createUserid=").append(createUserid);
		sb.append(", createUsername=").append(createUsername);
		sb.append(", column1=").append(column1);
		sb.append(", column2=").append(column2);
		sb.append("]");
		return sb.toString();
	}
}